In [1]:
import numpy as np

import diff_sensor_structures
import sensors
import em_stoch
import subspace_methods

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12
failing_sensors1 = np.array([0, 1, 2, 3, 4], dtype=np.int16)
gap_ratio1 = np.array([0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                                               Num_emitters1, 
                                                                               Q=Q_1,
                                                                               MUSIC_theta=MUSIC_theta1, 
                                                                               num_of_starts=10, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.80378761],P=[[4.8828125e-08+0.j]]
new_angles=[0.80378761]
new_P:
[[0.00100002+0.j]]
likelihood is -870.4013699741913 on iteration 0
new_angles=[0.80378761]
new_P:
[[0.002+0.j]]
1-th start
theta=[0.62809672],P=[[6.82086539e-08+0.j]]
new_angles=[0.62809672]
new_P:
[[0.00100004+0.j]]
likelihood is -870.3703510235397 on iteration 0
new_angles=[0.63652529]
new_P:
[[0.00200259+0.j]]
likelihood is -870.3229202992447 on iteration 1
new_angles=[0.64351668]
new_P:
[[0.00301676+0.j]]
likelihood is -870.2574883963157 on iteration 2
new_angles=[0.64915417]
new_P:
[[0.00405798+0.j]]
likelihood is -870.1767514850162 on iteration 3
new_angles=[0.65527209]
new_P:
[[0.00514762+0.j]]
likelihood is -870.0713184156422 on iteration 4
new_angles=[0.66020812]
new_P:
[[0.00631826+0.j]]
likelihood is -869.9518196120267 on iteration 5
new_angles=[0.66584631]
new_P:
[[0.00760901+0.j]]
likelihood is -869.8012138725377 on iteration 6
new_angles=[0.67042794]
new_P:
[[0.00908209+0.j]]
likelihood i

In [7]:
EM_theta1_rad, EM_P1

(array([0.69644619]), array([[0.85889812+0.j]]))

In [8]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5896372449038), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11
failing_sensors2 = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.int16)
gap_ratio2 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                                               Num_emitters2, 
                                                                               Q=Q_2,
                                                                               MUSIC_theta=MUSIC_theta2, 
                                                                               num_of_starts=20, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.81251426],P=[[4.8828125e-08+0.j]]
new_angles=[0.81251426]
new_P:
[[0.00100002+0.j]]
likelihood is -689.5858366251647 on iteration 0
new_angles=[0.81251426]
new_P:
[[0.00199942+0.j]]
1-th start
theta=[0.63682337],P=[[1.17743922e-07+4.63221143e-24j]]
new_angles=[0.63682337]
new_P:
[[0.00100004+0.j]]
likelihood is -689.542752465457 on iteration 0
new_angles=[0.64317969]
new_P:
[[0.00200334+0.j]]
likelihood is -689.4918290109238 on iteration 1
new_angles=[0.64789975]
new_P:
[[0.00302146+0.j]]
likelihood is -689.428710427439 on iteration 2
new_angles=[0.65280791]
new_P:
[[0.00407284+0.j]]
likelihood is -689.347488422542 on iteration 3
new_angles=[0.65818051]
new_P:
[[0.00518576+0.j]]
likelihood is -689.2414126395938 on iteration 4
new_angles=[0.66312769]
new_P:
[[0.00640285+0.j]]
likelihood is -689.1129430897106 on iteration 5
new_angles=[0.66809407]
new_P:
[[0.00778282+0.j]]
likelihood is -688.9541664931371 on iteration 6
new_angles=[0.67215948]
new_P:
[[0.00941403+0.j]

In [13]:
EM_theta2_rad, EM_P2

(array([0.70065544]), array([[0.72984998+0.j]]))

In [14]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.0606078496251), np.float64(-673.6467390084401))

In [15]:
lhd_list2

[np.float64(-689.4656264602315),
 np.float64(-689.3518048351036),
 np.float64(-689.235256331019),
 np.float64(-689.1129565562354),
 np.float64(-688.9811035456968),
 np.float64(-688.834661551721),
 np.float64(-688.6664293243715),
 np.float64(-688.4664536846983),
 np.float64(-688.2189534257384),
 np.float64(-687.8988675298015),
 np.float64(-687.4642141679846),
 np.float64(-686.8407865440585),
 np.float64(-685.8933305973329),
 np.float64(-684.375946636948),
 np.float64(-681.9040345090465),
 np.float64(-678.2554163864772),
 np.float64(-674.5553029896508),
 np.float64(-673.0606078496251)]

In [16]:
np.array(angles_list2)

array([[0.69944808],
       [0.69944808],
       [0.69944808],
       [0.69944808],
       [0.69944808],
       [0.69944808],
       [0.69944808],
       [0.69975194],
       [0.69984494],
       [0.69999396],
       [0.70021276],
       [0.70030004],
       [0.70041004],
       [0.70045761],
       [0.70051119],
       [0.70055911],
       [0.70059996],
       [0.70063903],
       [0.70065544]])

In [17]:
np.array(angles_list1)

array([[0.69671681],
       [0.69671681],
       [0.69671681],
       [0.69671681],
       [0.69671681],
       [0.69671681],
       [0.69666172],
       [0.69666172],
       [0.69666172],
       [0.69666172],
       [0.69666172],
       [0.69666172],
       [0.69662408],
       [0.69659766],
       [0.69658198],
       [0.69656934],
       [0.69656713],
       [0.69652783],
       [0.69651032],
       [0.69646848],
       [0.69644619]])