In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *

$x(t) = a(\theta) \cdot s(t) + n(t)$ - модель выходного вектора, где $a(\theta)$ - управляющий вектор, $s(t)$ - сигнал, $n(t)$ - шум. $s(t) \sim N(0, \Gamma)$, $n(t) \sim N(0, \Gamma)$

$$ P_{Bartlett} = \frac{a^H(\theta)\hat{R}a(\theta)}{a^H(\theta)a(\theta)} $$

$$ P_{CAPON}=\frac{1}{a^H(\theta)\hat{R}^{-1}a^H} $$

Для ULA (Uniform Linear Array) управляющий вектор определяется так:
$$
a = [1 \,\,\,\, e^{-2\pi j \frac{d}{\lambda}sin(\theta)} \,\,\,\, ... \,\,\,\, e^{-2\pi j (p-1) \frac{d}{\lambda}sin(\theta)}]
$$
где $j$ - мнимая единица, $d$ - расстояние между датчиками, $p$ - число датчиков, $\theta$ - DOA, $\lambda$ - длина волны.

In [2]:
# Some constants
# d/lambda
dist_ratio = 0.5
Num_sensors = 5
Num_emitters = 2
sample_size = 100
# DOA in degree
theta_degrees = np.array([20, 70])
# DOA in suitable form (radian)
theta = theta_degrees / 180 * np.pi
Gamma_signal = np.array([[2,0],[0,3]])
Gamma_noise = 0.1*np.eye(5, dtype=np.float64)

In [3]:
A = np.zeros((Num_sensors, Num_emitters),dtype=np.complex128)
for i in range(Num_emitters):
    A[:,i] = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors) * np.sin(theta[i]))

In [4]:
A

array([[ 1.        +0.j        ,  1.        +0.j        ],
       [ 0.47618256-0.87934645j, -0.98210585-0.18832978j],
       [-0.54650034-0.83745888j,  0.92906379+0.36991956j],
       [-0.99665042+0.08177982j, -0.8427721 -0.53827054j],
       [-0.40267475+0.91534313j,  0.72631904+0.68735774j]])

In [5]:
s = CN(Num_emitters,sample_size,Gamma_signal)

In [6]:
s

array([[ 1.37098278+1.59375458e-01j,  1.52868217-1.43078556e+00j],
       [-0.29418874-6.38166719e-01j, -0.50750234-1.14051813e+00j],
       [-0.58416578+1.82850847e-01j,  1.60505579-5.44588077e-01j],
       [ 0.6191076 +2.22363491e+00j, -1.10042138-7.67831276e-01j],
       [ 0.73548344-1.48060178e+00j, -0.37275482+8.24521152e-01j],
       [-0.73276875-1.31751665e+00j, -0.70724065-7.25767752e-01j],
       [ 1.61862192+1.31415027e+00j, -1.82076158-5.37746075e-01j],
       [ 1.36193289-2.14274420e-01j,  0.30363481-3.03844503e-01j],
       [-0.60348081+1.20061155e+00j, -0.24445913-7.76937780e-01j],
       [ 0.37550021+2.58449085e-01j,  0.47664569+1.84697529e-01j],
       [ 2.43988286+4.56900582e-01j, -0.1712839 +9.97612037e-01j],
       [ 2.14462182+1.92642511e-01j,  0.35200557+6.78288754e-01j],
       [ 0.05052897+3.54803580e-01j, -0.46573675+6.57967649e-01j],
       [-0.24311798-2.60070858e-03j, -1.74162474+5.20572931e-01j],
       [-0.28712201-8.93565440e-01j, -2.57406831+2.77083497e-0

In [7]:
A @ s[0][:, None]

array([[ 2.89966495-1.27141011j],
       [-0.97780291-0.01239053j],
       [ 1.33374665-1.99904206j],
       [-3.43790467+0.33625869j],
       [ 1.39582911+1.20228792j]])

In [8]:
n = CN(Num_sensors,sample_size,Gamma_noise)

In [9]:
n

array([[-0.00730659-6.10027101e-02j,  0.2953976 +8.45494189e-02j,
         0.26626587-8.90214159e-02j, -0.03787713-2.20647450e-01j,
         0.0135835 +3.72588582e-01j],
       [-0.14925441+2.27556949e-01j,  0.39651218-9.33836692e-02j,
         0.21930389+2.28907329e-01j, -0.05490822+3.36088778e-02j,
         0.31365985-4.95876539e-02j],
       [-0.2026432 -4.16105201e-01j, -0.05944204+1.26060355e-01j,
         0.41981948+1.01408064e-01j,  0.01790195+3.19049670e-01j,
        -0.39361921-1.29003822e-01j],
       [ 0.26615206-4.00027661e-01j,  0.13120882+1.26393495e-01j,
         0.03749989+5.31736814e-02j,  0.05098716+3.50877491e-01j,
        -0.15093433-1.40776236e-01j],
       [-0.32677131-1.33436562e-01j,  0.18430889-2.77641761e-01j,
        -0.17510898-2.84461463e-01j, -0.14577386+4.33794038e-03j,
         0.14502822+5.83738712e-02j],
       [-0.14265997-1.42768390e-02j,  0.22750086+7.19269188e-02j,
        -0.17687754+2.32721404e-01j,  0.13005182+3.76620327e-01j,
        -0.3277640

In [10]:
X = np.zeros((sample_size, 5))
for i in range(sample_size):
    X[i] = A @ s[i] + n[i]
print(X)

[[ 2.89235836e+00 -6.82405309e-01  1.60001252e+00 -3.47578180e+00
   1.40941261e+00]
 [-9.50945481e-01 -2.11175272e-02 -2.03962325e-01  1.04285767e-01
   1.43159911e+00]
 [ 8.18246811e-01 -1.85571917e+00  2.58484933e+00 -1.06067446e+00
   1.21434773e+00]
 [-2.15161722e-01  3.31748729e+00  8.23034335e-01 -2.33791674e-01
  -2.70710450e+00]
 [ 3.59573102e-02 -2.46062052e-01 -2.46831355e+00  2.52428324e-04
   3.66646360e-01]
 [-1.58266938e+00 -7.22082923e-01 -1.26838118e+00  1.17349568e+00
   1.15846296e+00]
 [-5.05498468e-01  3.47393578e+00 -1.19713573e+00 -3.25144794e-01
  -2.88715533e+00]
 [ 1.93499970e+00  1.82563383e-01  1.12871561e-01 -1.55994267e+00
  -2.03984149e-02]
 [-1.24613531e+00  8.33867801e-01  1.51572366e+00  3.91221371e-01
  -6.82364616e-01]
 [ 8.62152288e-01 -3.46345981e-01  6.76492168e-01 -3.89708449e-01
  -9.44008601e-01]
 [ 2.15622799e+00  2.05010967e+00 -1.31936784e+00 -1.97043310e+00
  -2.27362637e+00]
 [ 2.76029373e+00  8.18502262e-01 -1.12194628e+00 -2.20396148e+00

C:\Users\asus\AppData\Local\Temp\ipykernel_6544\3560522971.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  X[i] = A @ s[i] + n[i]


In [11]:
space_covariance_matrix(X)

array([[ 3.01161291, -1.4450161 ,  1.04802284, -2.64736895,  1.16241635],
       [-1.4450161 ,  3.3112037 , -1.21374484,  1.26300867, -3.15852169],
       [ 1.04802284, -1.21374484,  2.63889478, -1.16128671,  1.11797578],
       [-2.64736895,  1.26300867, -1.16128671,  2.87238046, -1.43772525],
       [ 1.16241635, -3.15852169,  1.11797578, -1.43772525,  3.48467028]])

# Задачи

* Смоделировать управляющий вектор для линейного массива

* Смоделировать сигнал (комплексный, гауссовский)

* Смоделировать шум (комплексный, гауссовский)

* Смоделировать выходной вектор

* Смоделировать формирование спектральной функции для определения пика