In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *
from functools import partial

In [2]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
# Истинное DOA в градусах
theta1_deg = rad_to_deg(theta1_rad[0])
GS_1 = np.array([[0.7]]) # Ковариация сигнала
GN_1 = 4.1*np.eye(5, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s1 = CN(Num_emitters1, sample_size1, GS_1)
n1 = CN(Num_sensors1, sample_size1, GN_1)
X1 = (A1 @ s1.T + n1.T).T

# ML1

In [3]:
theta_ML1, ML_func_val1 = multi_start_ML1(X1, L=5, M=1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [4]:
theta_ML1

array([0.5120428])

# ML2

In [5]:
theta_ML2, ML_func_val2 = multi_start_ML2(X1, GS_1, GN_1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [6]:
theta_ML2

array([0.5120428])

# EM

In [7]:
EM_theta1_rad, neglhd_1, K1, mu1 = multi_start_EM(X1, GS_1, GN_1, 10, max_iter=50, eps=1e-6)

0-th start
Iteration=1, theta_new=[-0.46968804], -likelihood = -80.61691
Iteration=2, theta_new=[-0.47225665], -likelihood = -80.67481
Iteration=3, theta_new=[-0.47456259], -likelihood = -80.72062
Iteration=4, theta_new=[-0.47669442], -likelihood = -80.75761
Iteration=5, theta_new=[-0.4785565], -likelihood = -80.78833
Iteration=6, theta_new=[-0.48023893], -likelihood = -80.81244
Iteration=7, theta_new=[-0.48173967], -likelihood = -80.83202
Iteration=8, theta_new=[-0.48315102], -likelihood = -80.84775
Iteration=9, theta_new=[-0.48437777], -likelihood = -80.86102
Iteration=10, theta_new=[-0.48551303], -likelihood = -80.87138
Iteration=11, theta_new=[-0.48655613], -likelihood = -80.87998
Iteration=12, theta_new=[-0.48750643], -likelihood = -80.88705
Iteration=13, theta_new=[-0.48826816], -likelihood = -80.89281
Iteration=14, theta_new=[-0.48903108], -likelihood = -80.89694
Iteration=15, theta_new=[-0.48969968], -likelihood = -80.90066
Iteration=16, theta_new=[-0.49027354], -likelihood = -

In [8]:
EM_theta1_rad

array([0.51177781])

# Истинный результат

In [9]:
theta1_rad

[0.5]