In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *
from functools import partial

# Case 1

Имеется 5 датчиков, 1 источник (дисперсия сигнала 0.7), и шум на каждом датчике имеет дисперсию 4.1.

In [2]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
theta1_deg = rad_to_deg(theta1_rad[0]) # Направление прибытия (DOA) в градусах
GS_1 = np.array([[0.7]]) # Ковариация сигнала
GN_1 = 4.1*np.eye(5, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s1 = CN(Num_emitters1, sample_size1, GS_1)
n1 = CN(Num_sensors1, sample_size1, GN_1)
X1 = (A1 @ s1.T + n1.T).T

## ML1

In [3]:
theta_ML1_Case1, ML1_func_val_Case1 = multi_start_ML1(X1, L=Num_sensors1, M=Num_emitters1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [4]:
theta_ML1_Case1

array([0.5120428])

## ML2

In [5]:
theta_ML2_Case1, ML2_func_val_Case1 = multi_start_ML2(X1, GS_1, GN_1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [6]:
theta_ML2_Case1

array([0.5120428])

## EM

In [7]:
EM_theta1_rad, neglhd_1, K1, mu1 = multi_start_EM(X1, GS_1, GN_1, 10, max_iter=50, eps=1e-6)

0-th start
Iteration=1, theta_new=[-2.04739902], -likelihood = -76.14479
Iteration=2, theta_new=[-2.03580242], -likelihood = -76.42059
Iteration=3, theta_new=[-2.02466913], -likelihood = -76.66261
Iteration=4, theta_new=[-2.01409102], -likelihood = -76.87475
Iteration=5, theta_new=[-2.0040599], -likelihood = -77.05813
Iteration=6, theta_new=[-1.99456802], -likelihood = -77.21588
Iteration=7, theta_new=[-1.98570544], -likelihood = -77.35098
Iteration=8, theta_new=[-1.97736703], -likelihood = -77.46500
Iteration=9, theta_new=[-1.96954638], -likelihood = -77.56186
Iteration=10, theta_new=[-1.96223752], -likelihood = -77.64381
Iteration=11, theta_new=[-1.95543484], -likelihood = -77.71285
Iteration=12, theta_new=[-1.94903767], -likelihood = -77.77076
Iteration=13, theta_new=[-1.94313726], -likelihood = -77.81982
Iteration=14, theta_new=[-1.93763423], -likelihood = -77.86058
Iteration=15, theta_new=[-1.93252524], -likelihood = -77.89483
Iteration=16, theta_new=[-1.92780716], -likelihood = -

In [8]:
EM_theta1_rad

array([0.51217753])

## True result

In [9]:
theta1_rad

[0.5]

# Case 2

Имеется 5 датчиков, 2 источника (дисперсии сигналов - 2 и 3), и шум на каждом датчике имеет дисперсию 7.1.

In [10]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([0.34906585, 1.22173048]) # Направление прибытия (DOA) в радианах
theta2_deg = rad_to_deg(theta2_rad) # Направление прибытия (DOA) в градусах
GS_2 = np.array([[2,0],[0,3]]) # Ковариация сигнала
GN_2 = 7.1*np.eye(5, dtype=np.float64) # Ковариация шума
A2 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors2).reshape(-1,1) * np.sin(theta2_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s2 = CN(Num_emitters2, sample_size2, GS_2)
n2 = CN(Num_sensors2, sample_size2, GN_2)
X2 = (A2 @ s2.T + n2.T).T

## ML1

In [11]:
theta_ML1_Case2, ML1_func_val_Case2 = multi_start_ML1(X2, L=Num_sensors2, M=Num_emitters2, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [12]:
theta_ML1_Case2

array([0.32881681, 1.23455554])

## ML2

In [13]:
theta_ML2_Case2, ML2_func_val_Case2 = multi_start_ML2(X2, GS_2, GN_2, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [14]:
theta_ML2_Case2

array([0.32583368, 1.24079361])

## EM

In [15]:
EM_theta2_rad, neglhd_2, K2, mu2 = multi_start_EM(X2, GS_2, GN_2, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[ 1.27155015 -1.90030329], -likelihood = -304.25906
Iteration=2, theta_new=[ 1.17114855 -1.93488894], -likelihood = -332.39634
Iteration=3, theta_new=[ 1.11405981 -1.95796297], -likelihood = -352.22894
Iteration=4, theta_new=[ 1.07808204 -1.96993502], -likelihood = -362.24368
Iteration=5, theta_new=[ 1.05360696 -1.97450179], -likelihood = -367.19982
Iteration=6, theta_new=[ 1.03600897 -1.97436414], -likelihood = -369.82559
Iteration=7, theta_new=[ 1.02263785 -1.97119983], -likelihood = -371.33267
Iteration=8, theta_new=[ 1.01202594 -1.96620075], -likelihood = -372.27781
Iteration=9, theta_new=[ 1.00319541 -1.96004483], -likelihood = -372.92092
Iteration=10, theta_new=[ 0.99560349 -1.9531671 ], -likelihood = -373.39519
Iteration=11, theta_new=[ 0.98886782 -1.94597964], -likelihood = -373.76619
Iteration=12, theta_new=[ 0.98276056 -1.93857289], -likelihood = -374.07421
Iteration=13, theta_new=[ 0.97714068 -1.93120617], -likelihood = -374.33884
Iteration=

In [16]:
EM_theta2_rad

array([0.32266979, 1.247151  ])

## True result

In [17]:
theta2_rad

array([0.34906585, 1.22173048])

# Case 3

Имеется 7 датчиков, 3 источника (дисперсии сигналов - 0.1, 0.5 и 0.9), и шум на каждом датчике имеет дисперсию 1.1.

In [18]:
Num_sensors3 = 7
Num_emitters3 = 3
sample_size3 = 100
theta3_rad = [0.5, 1.2, 1.6] # Направление прибытия (DOA) в радианах
theta3_deg = rad_to_deg(theta3_rad[0]) # Направление прибытия (DOA) в градусах
GS_3 = np.diag([0.1, 0.5, 0.9]) # Ковариация сигнала
GN_3 = 1.1*np.eye(7, dtype=np.float64) # Ковариация шума
A3 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors3).reshape(-1,1) * np.sin(theta3_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s3 = CN(Num_emitters3, sample_size3, GS_3)
n3 = CN(Num_sensors3, sample_size3, GN_3)
X3 = (A3 @ s3.T + n3.T).T

## ML1

In [19]:
theta_ML1_Case3, ML1_func_val_Case3 = multi_start_ML1(X3, L=Num_sensors3, M=Num_emitters3, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [20]:
theta_ML1_Case3

array([0.50012876, 1.14007338, 1.38774257])

## ML2

In [21]:
theta_ML2_Case3, ML2_func_val_Case3 = multi_start_ML2(X3, GS_3, GN_3, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [22]:
theta_ML2_Case3

array([ 0.50595641,  1.19839997, -1.46391099])

## EM

In [23]:
EM_theta3_rad, neglhd_3, K3, mu3 = multi_start_EM(X3, GS_3, GN_3, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-2.97277556  1.6741446  -0.07932455], -likelihood = -1004.82191
Iteration=2, theta_new=[-2.93996512  1.7020123  -0.06988788], -likelihood = -1030.28902
Iteration=3, theta_new=[-2.9204847   1.71973761 -0.0622255 ], -likelihood = -1043.07383
Iteration=4, theta_new=[-2.90780345  1.73181907 -0.05619312], -likelihood = -1048.89747
Iteration=5, theta_new=[-2.89907329  1.74028054 -0.05127877], -likelihood = -1051.80409
Iteration=6, theta_new=[-2.89296472  1.74630179 -0.04719994], -likelihood = -1053.38066
Iteration=7, theta_new=[-2.88870759  1.75064908 -0.04373884], -likelihood = -1054.28423
Iteration=8, theta_new=[-2.88573841  1.75388064 -0.04073418], -likelihood = -1054.83238
Iteration=9, theta_new=[-2.88371406  1.75622988 -0.03798564], -likelihood = -1055.18938
Iteration=10, theta_new=[-2.88252227  1.75802132 -0.03553064], -likelihood = -1055.44465
Iteration=11, theta_new=[-2.88191307  1.75937913 -0.03317272], -likelihood = -1055.63775
Iteration=12, theta

In [24]:
EM_theta3_rad

array([-0.54669212,  0.4857933 , -1.57077951])

## True result

In [25]:
theta3_rad

[0.5, 1.2, 1.6]

# Case 4

Имеется 7 датчиков, 3 источника (дисперсии сигналов - 0.5, 0.5 и 0.5), и шум на каждом датчике имеет дисперсию 1.1.

In [26]:
Num_sensors4 = 7
Num_emitters4 = 3
sample_size4 = 100
theta4_rad = [0.5, 1.1, -0.3] # Направление прибытия (DOA) в радианах
theta4_deg = rad_to_deg(theta4_rad[0]) # Направление прибытия (DOA) в градусах
GS_4 = np.diag([0.5, 0.5, 0.5]) # Ковариация сигнала
GN_4 = 1.1*np.eye(7, dtype=np.float64) # Ковариация шума
A4 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors4).reshape(-1,1) * np.sin(theta4_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s4 = CN(Num_emitters4, sample_size4, GS_4)
n4 = CN(Num_sensors4, sample_size4, GN_4)
X4 = (A4 @ s4.T + n4.T).T

## ML1

In [27]:
theta_ML1_Case4, ML1_func_val_Case4 = multi_start_ML1(X4, L=Num_sensors4, M=Num_emitters4, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [28]:
theta_ML1_Case4

array([ 1.11180646,  0.51075174, -0.29378152])

## ML2

In [29]:
theta_ML2_Case4, ML2_func_val_Case4 = multi_start_ML2(X4, GS_4, GN_4, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [30]:
theta_ML2_Case4

array([ 0.51031112, -0.29329847,  1.11202126])

## EM

In [31]:
EM_theta4_rad, neglhd_4, K4, mu4 = multi_start_EM(X4, GS_4, GN_4, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[ 0.94545693  0.31682385 -2.99287378], -likelihood = -682.10150
Iteration=2, theta_new=[ 0.98291068  0.35127351 -2.96455125], -likelihood = -851.11554
Iteration=3, theta_new=[ 1.01476584  0.38223122 -2.941683  ], -likelihood = -991.82409
Iteration=4, theta_new=[ 1.04044425  0.40904797 -2.92298546], -likelihood = -1095.63456
Iteration=5, theta_new=[ 1.06029811  0.43145591 -2.90765359], -likelihood = -1170.71380
Iteration=6, theta_new=[ 1.07507457  0.4496278  -2.89521531], -likelihood = -1222.84288
Iteration=7, theta_new=[ 1.0858495   0.46399166 -2.8851966 ], -likelihood = -1257.10565
Iteration=8, theta_new=[ 1.09355284  0.47517074 -2.87721324], -likelihood = -1278.59536
Iteration=9, theta_new=[ 1.09896925  0.48379911 -2.87095227], -likelihood = -1291.64003
Iteration=10, theta_new=[ 1.10281938  0.4903892  -2.86602146], -likelihood = -1299.39436
Iteration=11, theta_new=[ 1.10543101  0.49540997 -2.86213459], -likelihood = -1303.96870
Iteration=12, theta_ne

In [32]:
EM_theta4_rad

array([ 1.11014402,  0.51014441, -0.29193645])

## True Result

In [33]:
theta4_rad

[0.5, 1.1, -0.3]