In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *
from functools import partial

# Case 1

Имеется 5 датчиков, 1 источник (дисперсия сигнала 0.7), и шум на каждом датчике имеет дисперсию 4.1.

In [2]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
GS_1 = np.array([[0.7]]) # Ковариация сигнала
GN_1 = 4.1*np.eye(5, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s1 = CN(Num_emitters1, sample_size1, GS_1)
n1 = CN(Num_sensors1, sample_size1, GN_1)
X1 = (A1 @ s1.T + n1.T).T

## ML1

In [3]:
theta_ML1_Case1, ML1_func_val_Case1 = multi_start_ML1(X1, L=Num_sensors1, M=Num_emitters1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [4]:
np.rad2deg(theta_ML1_Case1)

array([29.33789075])

## ML2

In [5]:
theta_ML2_Case1, ML2_func_val_Case1 = multi_start_ML2(X1, GS_1, GN_1, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [6]:
np.rad2deg(theta_ML2_Case1)

array([29.33789135])

## EM

In [7]:
EM_theta1_rad, neglhd_1, K1, mu1 = multi_start_EM(X1, GS_1, GN_1, 10, max_iter=50, eps=1e-6)

0-th start
Iteration=1, theta_new=[2.52948019], -likelihood = -134.32180
Iteration=2, theta_new=[2.54627752], -likelihood = -137.83015
Iteration=3, theta_new=[2.5603268], -likelihood = -140.41476
Iteration=4, theta_new=[2.57201579], -likelihood = -142.27593
Iteration=5, theta_new=[2.58174876], -likelihood = -143.59597
Iteration=6, theta_new=[2.58981673], -likelihood = -144.52642
Iteration=7, theta_new=[2.59651889], -likelihood = -145.17617
Iteration=8, theta_new=[2.60209735], -likelihood = -145.62942
Iteration=9, theta_new=[2.60673488], -likelihood = -145.94539
Iteration=10, theta_new=[2.61055334], -likelihood = -146.16495
Iteration=11, theta_new=[2.61374005], -likelihood = -146.31598
Iteration=12, theta_new=[2.61642015], -likelihood = -146.42124
Iteration=13, theta_new=[2.61859199], -likelihood = -146.49504
Iteration=14, theta_new=[2.62044597], -likelihood = -146.54492
Iteration=15, theta_new=[2.62198139], -likelihood = -146.58044
Iteration=16, theta_new=[2.62326165], -likelihood = -1

In [8]:
np.rad2deg(EM_theta1_rad)

array([29.34438859])

## True result

In [9]:
np.rad2deg(theta1_rad)

array([28.64788976])

# Case 2

Имеется 5 датчиков, 2 источника (дисперсии сигналов - 2 и 3), и шум на каждом датчике имеет дисперсию 7.1.

In [10]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([0.34906585, 1.22173048]) # Направление прибытия (DOA) в радианах
GS_2 = np.array([[2,0],[0,3]]) # Ковариация сигнала
GN_2 = 7.1*np.eye(5, dtype=np.float64) # Ковариация шума
A2 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors2).reshape(-1,1) * np.sin(theta2_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s2 = CN(Num_emitters2, sample_size2, GS_2)
n2 = CN(Num_sensors2, sample_size2, GN_2)
X2 = (A2 @ s2.T + n2.T).T

## ML1

In [11]:
theta_ML1_Case2, ML1_func_val_Case2 = multi_start_ML1(X2, L=Num_sensors2, M=Num_emitters2, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [12]:
np.rad2deg(theta_ML1_Case2)

array([18.83981904, 70.73481887])

## ML2

In [13]:
theta_ML2_Case2, ML2_func_val_Case2 = multi_start_ML2(X2, GS_2, GN_2, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [14]:
np.rad2deg(theta_ML2_Case2)

array([18.66889475, 71.09223552])

## EM

In [15]:
EM_theta2_rad, neglhd_2, K2, mu2 = multi_start_EM(X2, GS_2, GN_2, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-3.1303273  -2.53652867], -likelihood = -190.05015
Iteration=2, theta_new=[-3.15046069 -2.54671298], -likelihood = -194.93169
Iteration=3, theta_new=[-3.17400368 -2.55609664], -likelihood = -201.55472
Iteration=4, theta_new=[-3.20085267 -2.56451057], -likelihood = -210.48532
Iteration=5, theta_new=[-3.23019587 -2.57197978], -likelihood = -222.12290
Iteration=6, theta_new=[-3.26062685 -2.57867621], -likelihood = -236.21526
Iteration=7, theta_new=[-3.29048825 -2.58505382], -likelihood = -251.66343
Iteration=8, theta_new=[-3.31832824 -2.59139691], -likelihood = -266.88168
Iteration=9, theta_new=[-3.34341398 -2.59786021], -likelihood = -280.46663
Iteration=10, theta_new=[-3.36528948 -2.60445822], -likelihood = -291.74641
Iteration=11, theta_new=[-3.38403642 -2.61101036], -likelihood = -300.55828
Iteration=12, theta_new=[-3.39991061 -2.61742205], -likelihood = -307.18318
Iteration=13, theta_new=[-3.41318362 -2.62344297], -likelihood = -312.03676
Iteration=

In [16]:
np.rad2deg(EM_theta2_rad)

array([18.39844309, 71.46658629])

## True result

In [17]:
np.rad2deg(theta2_rad)

array([19.99999998, 70.00000021])

# Case 3

Имеется 7 датчиков, 3 источника (дисперсии сигналов - 0.1, 0.5 и 0.9), и шум на каждом датчике имеет дисперсию 1.1.

In [18]:
Num_sensors3 = 7
Num_emitters3 = 3
sample_size3 = 100
theta3_rad = [0.5, 1.2, 1.6] # Направление прибытия (DOA) в радианах
GS_3 = np.diag([0.1, 0.5, 0.9]) # Ковариация сигнала
GN_3 = 1.1*np.eye(7, dtype=np.float64) # Ковариация шума
A3 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors3).reshape(-1,1) * np.sin(theta3_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s3 = CN(Num_emitters3, sample_size3, GS_3)
n3 = CN(Num_sensors3, sample_size3, GN_3)
X3 = (A3 @ s3.T + n3.T).T

## ML1

In [19]:
theta_ML1_Case3, ML1_func_val_Case3 = multi_start_ML1(X3, L=Num_sensors3, M=Num_emitters3, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [20]:
np.rad2deg(theta_ML1_Case3)

array([ 59.89284651, -63.39567897, -63.63814575])

## ML2

In [21]:
theta_ML2_Case3, ML2_func_val_Case3 = multi_start_ML2(X3, GS_3, GN_3, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [22]:
np.rad2deg(theta_ML2_Case3)

array([ 28.98916692,  68.66326015, -83.8759217 ])

## EM

In [23]:
EM_theta3_rad, neglhd_3, K3, mu3 = multi_start_EM(X3, GS_3, GN_3, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-1.42711028  1.1634118  -1.70846055], -likelihood = -1026.35249
Iteration=2, theta_new=[-1.39143101  1.13372256 -1.74405921], -likelihood = -1049.43714
Iteration=3, theta_new=[-1.37151671  1.11364441 -1.76331327], -likelihood = -1059.11174
Iteration=4, theta_new=[-1.35917434  1.09922836 -1.77454046], -likelihood = -1063.83613
Iteration=5, theta_new=[-1.35124816  1.08845049 -1.78112251], -likelihood = -1066.39239
Iteration=6, theta_new=[-1.34578959  1.08015411 -1.78472754], -likelihood = -1067.89448
Iteration=7, theta_new=[-1.34176561  1.07359617 -1.78634738], -likelihood = -1068.84250
Iteration=8, theta_new=[-1.33849961  1.06828452 -1.786624  ], -likelihood = -1069.48384
Iteration=9, theta_new=[-1.33540468  1.06388211 -1.7859547 ], -likelihood = -1069.94724
Iteration=10, theta_new=[-1.3319661   1.06015281 -1.78459397], -likelihood = -1070.30307
Iteration=11, theta_new=[-1.32782885  1.05693329 -1.78270579], -likelihood = -1070.59199
Iteration=12, theta

In [24]:
np.rad2deg(EM_theta3_rad)

array([-57.21971209,  33.39098506,  76.54549077])

## True result

In [25]:
np.rad2deg(theta3_rad)

array([28.64788976, 68.75493542, 91.67324722])

# Case 4

Имеется 7 датчиков, 3 источника (дисперсии сигналов - 0.5, 0.5 и 0.5), и шум на каждом датчике имеет дисперсию 1.1.

In [26]:
Num_sensors4 = 7
Num_emitters4 = 3
sample_size4 = 100
theta4_rad = [0.5, 1.1, -0.3] # Направление прибытия (DOA) в радианах
GS_4 = np.diag([0.5, 0.5, 0.5]) # Ковариация сигнала
GN_4 = 1.1*np.eye(7, dtype=np.float64) # Ковариация шума
A4 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors4).reshape(-1,1) * np.sin(theta4_rad).reshape(1,-1)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
s4 = CN(Num_emitters4, sample_size4, GS_4)
n4 = CN(Num_sensors4, sample_size4, GN_4)
X4 = (A4 @ s4.T + n4.T).T

## ML1

In [27]:
theta_ML1_Case4, ML1_func_val_Case4 = multi_start_ML1(X4, L=Num_sensors4, M=Num_emitters4, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [28]:
np.rad2deg(theta_ML1_Case4)

array([ 63.70182371,  29.26391723, -16.83244179])

## ML2

In [29]:
theta_ML2_Case4, ML2_func_val_Case4 = multi_start_ML2(X4, GS_4, GN_4, method='CG')

0-th start
1-th start
2-th start
3-th start
4-th start
5-th start
6-th start
7-th start
8-th start
9-th start
10-th start
11-th start
12-th start
13-th start
14-th start
15-th start
16-th start
17-th start
18-th start
19-th start


In [30]:
np.rad2deg(theta_ML2_Case4)

array([-16.80476507,  29.23867373,  63.71412425])

## EM

In [31]:
EM_theta4_rad, neglhd_4, K4, mu4 = multi_start_EM(X4, GS_4, GN_4, 30, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-0.84722277  1.93215421  1.38309335], -likelihood = -537.82591
Iteration=2, theta_new=[-0.8459026   1.99451153  1.48109374], -likelihood = -579.83935
Iteration=3, theta_new=[-0.83944142  2.03047896  1.57077196], -likelihood = -618.81225
Iteration=4, theta_new=[-0.83206531  2.05531716  1.57083689], -likelihood = -635.49397
Iteration=5, theta_new=[-0.82531497  2.07421447  1.57080311], -likelihood = -644.28424
Iteration=6, theta_new=[-0.81944663  2.08883128  1.57083205], -likelihood = -649.65809
Iteration=7, theta_new=[-0.81445639  2.10026823  1.57076955], -likelihood = -652.96765
Iteration=8, theta_new=[-0.81025832  2.10930487  1.57066991], -likelihood = -655.02444
Iteration=9, theta_new=[-0.80675212  2.11649028  1.57081021], -likelihood = -656.31484
Iteration=10, theta_new=[-0.80382809  2.12223697  1.5708123 ], -likelihood = -657.12952
Iteration=11, theta_new=[-0.80138711  2.126848    1.57075147], -likelihood = -657.64654
Iteration=12, theta_new=[-0.79

In [32]:
np.rad2deg(EM_theta4_rad)

array([-16.98336345,  29.42700468,  63.22060413])

## True Result

In [33]:
np.rad2deg(theta4_rad)

array([ 28.64788976,  63.02535746, -17.18873385])