In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *
from functools import partial

In [2]:
# Отношение расстояния между датчиками к длине волны
dist_ratio = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1 = [0.5] # Направление прибытия (DOA) в радианах
GS_1 = np.array([[0.7]]) # Ковариация сигнала
GN_1 = 0.8*np.eye(5, dtype=np.float64) # Ковариация шума

In [4]:
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1).reshape(1,-1))

In [5]:
A1

array([[ 1.        +0.j        ],
       [ 0.06459158-0.99791178j],
       [-0.99165586-0.1289134j ],
       [-0.19269681+0.98125834j],
       [ 0.96676267+0.25567545j]])

In [6]:
s1 = CN(Num_emitters1, sample_size1, GS_1)
n1 = CN(Num_sensors1, sample_size1, GN_1)
X1 = (A1 @ s1.T + n1.T).T

In [7]:
print(X1.shape)

(100, 5)


In [8]:
est_theta1, neglhd_1 = multi_start(10, X1, GS_1, GN_1, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-2.43273311], -likelihood = -89.11899
Iteration=2, theta_new=[-2.44579955], -likelihood = -90.01418
Iteration=3, theta_new=[-2.46030954], -likelihood = -91.19930
Iteration=4, theta_new=[-2.47592674], -likelihood = -92.66496
Iteration=5, theta_new=[-2.49200576], -likelihood = -94.35921
Iteration=6, theta_new=[-2.50794583], -likelihood = -96.16209
Iteration=7, theta_new=[-2.52319189], -likelihood = -97.94067
Iteration=8, theta_new=[-2.5372986], -likelihood = -99.57540
Iteration=9, theta_new=[-2.55005943], -likelihood = -100.98551
Iteration=10, theta_new=[-2.561328], -likelihood = -102.14514
Iteration=11, theta_new=[-2.57114559], -likelihood = -103.05767
Iteration=12, theta_new=[-2.57961983], -likelihood = -103.75543
Iteration=13, theta_new=[-2.58686241], -likelihood = -104.27795
Iteration=14, theta_new=[-2.59298853], -likelihood = -104.66206
Iteration=15, theta_new=[-2.59817957], -likelihood = -104.93991
Iteration=16, theta_new=[-2.60255639], -likelihoo

In [9]:
np.abs(est_theta1-theta1)

array([2.13768526])

In [10]:
np.abs(np.sin(est_theta1)-np.sin(theta1))

array([0.00342539])

In [11]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2 = np.array([0.34906585, 1.22173048])
GS_2 = np.array([[2,0],[0,3]]) # Ковариация сигнала
GN_2 = 0.1*np.eye(5, dtype=np.float64) # Ковариация шума

In [12]:
# Матрица управляющих векторов
A2 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors2).reshape(-1,1) * np.sin(theta2).reshape(1,-1))

In [13]:
A2

array([[ 1.        +0.j        ,  1.        +0.j        ],
       [ 0.47618256-0.87934645j, -0.98210585-0.18832978j],
       [-0.54650034-0.83745888j,  0.92906379+0.36991955j],
       [-0.99665042+0.08177982j, -0.84277211-0.53827054j],
       [-0.40267475+0.91534313j,  0.72631905+0.68735773j]])

In [14]:
s2 = CN(Num_emitters2, sample_size2, GS_2)
n2 = CN(Num_sensors2, sample_size2, GN_2)
X2 = (A2 @ s2.T + n2.T).T

In [ ]:
est_theta2, neglhd_2 = multi_start(10, X2, GS_2, GN_2, max_iter=20, eps=1e-6)

0-th start
Iteration=1, theta_new=[-1.85575408 -1.57082003], -likelihood = -12739.93076
Iteration=2, theta_new=[-1.90052173 -1.4986572 ], -likelihood = -13517.25381
Iteration=3, theta_new=[-1.93494213 -1.46892526], -likelihood = -13623.53529
Iteration=4, theta_new=[-1.96201943 -1.44967579], -likelihood = -13681.95767
Iteration=5, theta_new=[-1.98355059 -1.43711446], -likelihood = -13717.73916
Iteration=6, theta_new=[-2.00091464 -1.42921426], -likelihood = -13740.62377
Iteration=7, theta_new=[-2.01506458 -1.42480672], -likelihood = -13755.71628
Iteration=8, theta_new=[-2.02676254 -1.42301646], -likelihood = -13765.92760
Iteration=9, theta_new=[-2.03660276 -1.42318493], -likelihood = -13773.06177
Iteration=10, theta_new=[-2.04497511 -1.42491101], -likelihood = -13778.23893
Iteration=11, theta_new=[-2.05219249 -1.42795195], -likelihood = -13782.13543
Iteration=12, theta_new=[-2.05849264 -1.43202066], -likelihood = -13785.19339
Iteration=13, theta_new=[-2.06412638 -1.43691895], -likelihood

In [ ]:
np.abs(est_theta2-theta2)

In [ ]:
np.abs(np.sin(est_theta2)-np.sin(theta2))

In [ ]:
W1, W2 = goal_function(X1, GS_1, GN_2, 50)

In [ ]:
plt.title("График функции, подлежащей максимизации, на первом шаге ЕМ-алгоритма")
plt.plot(W1, W2.real, color='green')