In [1]:
import numpy as np
import sensors
import em_stoch

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.7] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Направление прибытия (DOA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация шума
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

In [5]:
EM_theta1_rad, EM_P1, lhd_1 = em_stoch.multi_start_EM(X1, Num_emitters1, Q_1, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836]
likelihood is -1084.745830993925 on iteration 0
likelihood is -1067.7622827049267 on iteration 1
likelihood is -1061.4103474403887 on iteration 2
likelihood is -1058.3046445419818 on iteration 3
likelihood is -1056.5689225778865 on iteration 4
likelihood is -1055.5212158698762 on iteration 5
likelihood is -1054.852782822986 on iteration 6
likelihood is -1054.4067845809225 on iteration 7
likelihood is -1054.0981383979815 on iteration 8
likelihood is -1053.87833658643 on iteration 9
likelihood is -1053.7172914607193 on iteration 10
likelihood is -1053.5963350443776 on iteration 11
likelihood is -1053.5041598097578 on iteration 12
likelihood is -1053.43298227006 on iteration 13
likelihood is -1053.3767669948909 on iteration 14
likelihood is -1053.3319453802706 on iteration 15
likelihood is -1053.2955410839013 on iteration 16
likelihood is -1053.2657399899736 on iteration 17
likelihood is -1053.2411876840729 on iteration 18
likelihood is -1053.22100

In [6]:
EM_theta1_rad

array([0.69180963])

In [7]:
EM_P1

array([[1.11375714]])

In [8]:
EM_theta1_deg = np.rad2deg(EM_theta1_rad)

In [9]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(EM_theta1_deg-theta1_deg)},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.46927374],
Погрешность в смысле разности синусов углов:       [0.00628588].


In [10]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([-0.5, 0.7], dtype=np.float64) # Направление прибытия (DOA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Направление прибытия (DOA) в градусах
P_2 = 1 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация шума
Q_2 = 1.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шума
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
n2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + n2.T).T

In [11]:
X2_with_mv = sensors.MCAR(X2, [2,4], [40, 40])

In [12]:
EM_theta2_rad, EM_P2, lhd_2 = em_stoch.multi_start_EM(X2, Num_emitters2, Q_2, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836  0.30670429]
likelihood is -1313.3547051920666 on iteration 0
likelihood is -1476.3825632065711 on iteration 1
likelihood is -1367.82703587524 on iteration 2
likelihood is -1070.2562645563503 on iteration 3
likelihood is -1299.6837770581808 on iteration 4
likelihood is -1211.4480591533895 on iteration 5
likelihood is -1185.843210703305 on iteration 6
likelihood is -1176.3587473452858 on iteration 7
likelihood is -1026.0355759279955 on iteration 8
likelihood is -949.990192039721 on iteration 9
likelihood is -906.6805769505663 on iteration 10
likelihood is -894.848224594648 on iteration 11
likelihood is -892.9307295961936 on iteration 12
likelihood is -892.6166708701554 on iteration 13
likelihood is -892.526313923966 on iteration 14
likelihood is -892.4852401603977 on iteration 15
likelihood is -892.4640444711346 on iteration 16
1-th start
Initial theta = [-2.86887136  0.27272129]
likelihood is -1377.1911203496652 on iteration 0
likelihood is -1275

In [13]:
EM_theta2_deg = np.rad2deg(EM_theta2_rad)

In [14]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(np.sort(EM_theta2_deg)-np.sort(theta2_deg))},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta2_rad)-np.sin(theta2_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.80922856 0.51410521],
Погрешность в смысле разности синусов углов:       [0.01234649 0.00688864].


In [15]:
EM_theta2_rad

array([-0.5141237 ,  0.69102717])

In [16]:
EM_P2

array([[ 1.16014464,  0.        ],
       [-0.        ,  0.99069638]])