In [29]:
import numpy as np

import diff_sensor_structures
import sensors
import em_stoch
import subspace_methods

In [30]:
DIST_RATIO = 0.5

In [31]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12
failing_sensors1 = np.array([0, 1, 2, 3, 4], dtype=np.int16)
gap_ratio1 = np.array([0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [32]:
MUSIC_theta1

array([0.71558499])

In [33]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [34]:
EM_theta1_rad, EM_P1, lhd_1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                      Num_emitters1, 
                                                      Q=Q_1,
                                                      MUSIC_theta=MUSIC_theta1, 
                                                      num_of_starts=10, 
                                                      max_iter=20, 
                                                      rtol=1e-5)

0-th start
theta=[0.80378761],P=[[4.8828125e-08+0.j]]
new_angles=[0.80378761]
new_P:
[[0.00100002+0.j]]
likelihood is -870.4013699741913 on iteration 0
new_angles=[0.80378761]
new_P:
[[0.002+0.j]]
1-th start
theta=[0.62809672],P=[[6.82086539e-08+0.j]]
new_angles=[0.62809672]
new_P:
[[0.00100004+0.j]]
likelihood is -870.3703510235397 on iteration 0
new_angles=[0.62809672]
new_P:
[[0.00200259+0.j]]
likelihood is -870.3397588975417 on iteration 1
new_angles=[0.6339026]
new_P:
[[0.00301397+0.j]]
likelihood is -870.2925733083172 on iteration 2
new_angles=[0.63924299]
new_P:
[[0.00404641+0.j]]
likelihood is -870.2313800713952 on iteration 3
new_angles=[0.64411916]
new_P:
[[0.00511756+0.j]]
likelihood is -870.1552450130418 on iteration 4
new_angles=[0.65035471]
new_P:
[[0.00625178+0.j]]
likelihood is -870.0473620399755 on iteration 5
new_angles=[0.65630934]
new_P:
[[0.00749007+0.j]]
likelihood is -869.9136831363899 on iteration 6
new_angles=[0.66184064]
new_P:
[[0.00888574+0.j]]
likelihood is

In [35]:
EM_theta1_rad, EM_P1

(array([0.69633739]), array([[0.85892521+0.j]]))

In [36]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5894937632039), np.float64(-852.4011191641745))

In [37]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11
failing_sensors2 = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.int16)
gap_ratio2 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [38]:
MUSIC_theta2

array([0.72431164])

In [39]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [40]:
EM_theta2_rad, EM_P2, lhd_2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                      Num_emitters2, 
                                                      Q=Q_2,
                                                      MUSIC_theta=MUSIC_theta2, 
                                                      num_of_starts=20, 
                                                      max_iter=20, 
                                                      rtol=1e-5)

0-th start
theta=[0.81251426],P=[[4.8828125e-08+0.j]]
new_angles=[0.81251426]
new_P:
[[0.00100002+0.j]]
likelihood is -689.5858366251647 on iteration 0
new_angles=[0.81251426]
new_P:
[[0.00199942+0.j]]
1-th start
theta=[0.63682337],P=[[1.17743922e-07+4.63221143e-24j]]
new_angles=[0.63682337]
new_P:
[[0.00100004+0.j]]
likelihood is -689.542752465457 on iteration 0
new_angles=[0.63682337]
new_P:
[[0.00200334+0.j]]
likelihood is -689.5065020930143 on iteration 1
new_angles=[0.64264951]
new_P:
[[0.00301881+0.j]]
likelihood is -689.450198309814 on iteration 2
new_angles=[0.64753817]
new_P:
[[0.00406431+0.j]]
likelihood is -689.3798550308624 on iteration 3
new_angles=[0.6524355]
new_P:
[[0.00516515+0.j]]
likelihood is -689.2897917056298 on iteration 4
new_angles=[0.65738678]
new_P:
[[0.0063589+0.j]]
likelihood is -689.1753199052384 on iteration 5
new_angles=[0.66233092]
new_P:
[[0.00770036+0.j]]
likelihood is -689.0315995121632 on iteration 6
new_angles=[0.66712927]
new_P:
[[0.00927039+0.j]]

In [41]:
EM_theta2_rad, EM_P2

(array([0.70066336]), array([[0.72991514+0.j]]))

In [42]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.0605614224675), np.float64(-673.6467390084401))