In [1]:
import numpy as np

import diff_sensor_structures
import sensors
import em_stoch
import subspace_methods

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12
failing_sensors1 = np.array([0, 1, 2, 3, 4], dtype=np.int16)
gap_ratio1 = np.array([0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                                               Num_emitters1, 
                                                                               Q=Q_1,
                                                                               MUSIC_theta=MUSIC_theta1, 
                                                                               num_of_starts=1, 
                                                                               max_iter=25, 
                                                                               rtol=1e-5)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Initial angles = [0.71558499]
likelihood is -870.3064393934375 on iteration 0
likelihood is -870.2104097097736 on iteration 1
likelihood is -870.1001175947267 on iteration 2
likelihood is -869.9877652745258 on iteration 3
likelihood is -869.8658170976637 on iteration 4
likelihood is -869.7362841091547 on iteration 5
likelihood is -869.5919726387026 on iteration 6
likelihood is -869.4267679454484 on iteration 7
likelihood is -869.2334065709836 on iteration 8
likelihood is -869.0004377943346 on iteration 9
likelihood is -868.708478948862 on iteration 10
likelihood is -868.3277637157865 on iteration 11
likelihood is -867.8095990393304 on iteration 12
likelihood is -867.0685929537905 on iteration 13
likelihood is -865.9510041789777 on iteration 14
likelihood is -864.1865870742085 on iteration 15
likelihood is -861.3632050053997 on iteration 16
likelihood is -857.230740527106 on iteration 17
likelihood is -852.8559818412223 

In [7]:
EM_theta1_rad, EM_P1

(array([0.69675959]), array([[1.28643425+0.j]]))

In [8]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5396982225466), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11
failing_sensors2 = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.int16)
gap_ratio2 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                                               Num_emitters2, 
                                                                               Q=Q_2,
                                                                               MUSIC_theta=MUSIC_theta2, 
                                                                               num_of_starts=1, 
                                                                               max_iter=25, 
                                                                               rtol=1e-5)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Initial angles = [0.72431164]
likelihood is -689.483063070951 on iteration 0
likelihood is -689.3709874215322 on iteration 1
likelihood is -689.2520227740401 on iteration 2
likelihood is -689.1343667302003 on iteration 3
likelihood is -689.0004346377918 on iteration 4
likelihood is -688.8515113630011 on iteration 5
likelihood is -688.6831555947198 on iteration 6
likelihood is -688.4827203547131 on iteration 7
likelihood is -688.2357218808453 on iteration 8
likelihood is -687.9182238327068 on iteration 9
likelihood is -687.4881716776484 on iteration 10
likelihood is -686.8723408899971 on iteration 11
likelihood is -685.9391648978449 on iteration 12
likelihood is -684.4467316291505 on iteration 13
likelihood is -682.0134668316044 on iteration 14
likelihood is -678.3968959998414 on iteration 15
likelihood is -674.6574180894964 on iteration 16
likelihood is -673.075268401642 on iteration 17
best_start=0


In [13]:
EM_theta2_rad, EM_P2

(array([0.70168609]), array([[0.71697303+0.j]]))

In [14]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.075268401642), np.float64(-673.6467390084401))

In [15]:
lhd_list2

[np.float64(-689.483063070951),
 np.float64(-689.3709874215322),
 np.float64(-689.2520227740401),
 np.float64(-689.1343667302003),
 np.float64(-689.0004346377918),
 np.float64(-688.8515113630011),
 np.float64(-688.6831555947198),
 np.float64(-688.4827203547131),
 np.float64(-688.2357218808453),
 np.float64(-687.9182238327068),
 np.float64(-687.4881716776484),
 np.float64(-686.8723408899971),
 np.float64(-685.9391648978449),
 np.float64(-684.4467316291505),
 np.float64(-682.0134668316044),
 np.float64(-678.3968959998414),
 np.float64(-674.6574180894964),
 np.float64(-673.075268401642)]

In [16]:
np.array(angles_list2)

array([[0.72431164],
       [0.72431164],
       [0.71789565],
       [0.71355919],
       [0.71307021],
       [0.71079967],
       [0.70879466],
       [0.70759797],
       [0.706371  ],
       [0.70533598],
       [0.70464982],
       [0.70406922],
       [0.7034473 ],
       [0.7030265 ],
       [0.70264735],
       [0.70232748],
       [0.70206975],
       [0.70185989],
       [0.70168609]])

In [17]:
np.array(angles_list1)

array([[0.71558499],
       [0.71558499],
       [0.71498939],
       [0.71024057],
       [0.70798393],
       [0.70541575],
       [0.70416001],
       [0.70297307],
       [0.70169374],
       [0.70060075],
       [0.69990536],
       [0.69927791],
       [0.69864006],
       [0.69820689],
       [0.69799232],
       [0.6976854 ],
       [0.6974587 ],
       [0.69726486],
       [0.69709388],
       [0.69696005],
       [0.69685427],
       [0.69675959]])