In [1]:
import numpy as np

import diff_sensor_structures
import sensors
import em_stoch
import subspace_methods

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12

failing_sensors1 = np.arange(5)
gap_ratio1 = 0.5 * np.ones_like(failing_sensors1, dtype=np.float32)

theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                                               Num_emitters1, 
                                                                               Q=Q_1,
                                                                               MUSIC_theta=MUSIC_theta1, 
                                                                               num_of_starts=10, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Initial angles = [0.71558499]
likelihood is -870.3064393934375 on iteration 0
likelihood is -870.2116588216295 on iteration 1
likelihood is -870.103793774924 on iteration 2
likelihood is -869.9901076595419 on iteration 3
likelihood is -869.8685961535426 on iteration 4
likelihood is -869.7367099905118 on iteration 5
likelihood is -869.5903538779986 on iteration 6
likelihood is -869.4254106176447 on iteration 7
likelihood is -869.2317840813287 on iteration 8
likelihood is -868.9988523292069 on iteration 9
likelihood is -868.7067695434375 on iteration 10
likelihood is -868.3264048432821 on iteration 11
likelihood is -867.8081349577396 on iteration 12
likelihood is -867.0664256708633 on iteration 13
likelihood is -865.9483337486055 on iteration 14
likelihood is -864.1826784337128 on iteration 15
likelihood is -861.3574484619562 on iteration 16
likelihood is -857.2233543538327 on iteration 17
likelihood is -852.8499634762443

In [7]:
EM_theta1_rad, EM_P1

(array([0.6962358]), array([[0.85808585+0.j]]))

In [8]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5910266391377), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11

failing_sensors2 = np.arange(8)
gap_ratio2 = 0.5 * np.ones_like(failing_sensors2, dtype=np.float32)

theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                                               Num_emitters2, 
                                                                               Q=Q_2,
                                                                               MUSIC_theta=MUSIC_theta2, 
                                                                               num_of_starts=20, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Initial angles = [0.72431164]
likelihood is -689.483063070951 on iteration 0
likelihood is -689.368354938845 on iteration 1
likelihood is -689.2605268955323 on iteration 2
likelihood is -689.1424169859715 on iteration 3
likelihood is -689.0197485378706 on iteration 4
likelihood is -688.8669613886939 on iteration 5
likelihood is -688.6961227855542 on iteration 6
likelihood is -688.4940480907271 on iteration 7
likelihood is -688.2476340422891 on iteration 8
likelihood is -687.9303831602817 on iteration 9
likelihood is -687.5016207209967 on iteration 10
likelihood is -686.8905143923773 on iteration 11
likelihood is -685.965719134779 on iteration 12
likelihood is -684.4883231892187 on iteration 13
likelihood is -682.0784254801724 on iteration 14
likelihood is -678.4816538011912 on iteration 15
likelihood is -674.7188238324068 on iteration 16
likelihood is -673.0826731697321 on iteration 17
1-th start
theta=[0.76634416],P=[[4

In [13]:
EM_theta2_rad, EM_P2

(array([0.70088911]), array([[0.72979926+0.j]]))

In [14]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.0607651045415), np.float64(-673.6467390084401))

In [15]:
lhd_list2

[np.float64(-689.4657255022213),
 np.float64(-689.352003354143),
 np.float64(-689.2355598808695),
 np.float64(-689.1130649676165),
 np.float64(-688.981243619127),
 np.float64(-688.834713883687),
 np.float64(-688.6664400442633),
 np.float64(-688.4665113814211),
 np.float64(-688.2189652061207),
 np.float64(-687.8988904408251),
 np.float64(-687.464256147106),
 np.float64(-686.8408518483232),
 np.float64(-685.8934403389032),
 np.float64(-684.3761722011797),
 np.float64(-681.904406189614),
 np.float64(-678.2559543821535),
 np.float64(-674.5557584258886),
 np.float64(-673.0607651045415)]

In [16]:
np.array(angles_list2)

array([[0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7023308 ],
       [0.7023308 ],
       [0.70213636],
       [0.70174859],
       [0.70172838],
       [0.70148545],
       [0.70125653],
       [0.70117529],
       [0.70104884],
       [0.70100148],
       [0.70100148],
       [0.70095942],
       [0.70094713],
       [0.7009177 ],
       [0.70088911]])

In [17]:
np.array(angles_list1)

array([[0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69424228],
       [0.69424228],
       [0.69425745],
       [0.69452987],
       [0.69467371],
       [0.69496645],
       [0.69521674],
       [0.69552948],
       [0.69563484],
       [0.695764  ],
       [0.69589678],
       [0.6959805 ],
       [0.69603748],
       [0.69612575],
       [0.69616896],
       [0.69620569],
       [0.6962358 ]])