In [1]:
import numpy as np

import diff_sensor_structures
import sensors
import em_stoch
import subspace_methods

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12
failing_sensors1 = np.array([0, 1, 2, 3, 4], dtype=np.int16)
gap_ratio1 = np.array([0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                                               Num_emitters1, 
                                                                               Q=Q_1,
                                                                               MUSIC_theta=MUSIC_theta1, 
                                                                               num_of_starts=10, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Initial angles = [0.71558499]
likelihood is -870.3064393934375 on iteration 0
likelihood is -870.2095011583305 on iteration 1
likelihood is -870.1020975251839 on iteration 2
likelihood is -869.9869037806478 on iteration 3
likelihood is -869.8654645440834 on iteration 4
likelihood is -869.7330992797224 on iteration 5
likelihood is -869.5875745241739 on iteration 6
likelihood is -869.4234000803935 on iteration 7
likelihood is -869.2305064985298 on iteration 8
likelihood is -868.9973064841059 on iteration 9
likelihood is -868.7048981595599 on iteration 10
likelihood is -868.3240836404314 on iteration 11
likelihood is -867.8050335224876 on iteration 12
likelihood is -867.0623583154716 on iteration 13
likelihood is -865.9420808415196 on iteration 14
likelihood is -864.1728848275934 on iteration 15
likelihood is -861.3421794666327 on iteration 16
likelihood is -857.2034810073116 on iteration 17
likelihood is -852.834706423492

In [7]:
EM_theta1_rad, EM_P1

(array([0.6962773]), array([[0.8585072+0.j]]))

In [8]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5902441310429), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11
failing_sensors2 = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=np.int16)
gap_ratio2 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], dtype=np.float32)
theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                                               Num_emitters2, 
                                                                               Q=Q_2,
                                                                               MUSIC_theta=MUSIC_theta2, 
                                                                               num_of_starts=20, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Initial angles = [0.72431164]
likelihood is -689.483063070951 on iteration 0
likelihood is -689.3868727803281 on iteration 1
likelihood is -689.2710510318451 on iteration 2
likelihood is -689.1443306322394 on iteration 3
likelihood is -689.0114793587493 on iteration 4
likelihood is -688.8620035189796 on iteration 5
likelihood is -688.6889899164013 on iteration 6
likelihood is -688.4879511180192 on iteration 7
likelihood is -688.2424220579322 on iteration 8
likelihood is -687.9260858269392 on iteration 9
likelihood is -687.4976972369675 on iteration 10
likelihood is -686.885829120551 on iteration 11
likelihood is -685.9588145359849 on iteration 12
likelihood is -684.4782320298359 on iteration 13
likelihood is -682.0625550641477 on iteration 14
likelihood is -678.4607733142082 on iteration 15
likelihood is -674.7036656816141 on iteration 16
likelihood is -673.0809037459098 on iteration 17
1-th start
theta=[0.76634416],P=[[

In [13]:
EM_theta2_rad, EM_P2

(array([0.70095629]), array([[0.72967058+0.j]]))

In [14]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.0610118618508), np.float64(-673.6467390084401))

In [15]:
lhd_list2

[np.float64(-689.4657255022213),
 np.float64(-689.3518835860682),
 np.float64(-689.2353762214767),
 np.float64(-689.1131217581909),
 np.float64(-688.9813207481523),
 np.float64(-688.8348862714762),
 np.float64(-688.6667241323851),
 np.float64(-688.4666064896782),
 np.float64(-688.2191432960745),
 np.float64(-687.8991997027118),
 np.float64(-687.4645162744796),
 np.float64(-686.841299476858),
 np.float64(-685.8940026385463),
 np.float64(-684.3769126941946),
 np.float64(-681.9055695692822),
 np.float64(-678.2574460122166),
 np.float64(-674.5568715968758),
 np.float64(-673.0610118618508)]

In [16]:
np.array(angles_list2)

array([[0.7029336 ],
       [0.7029336 ],
       [0.70247429],
       [0.70247429],
       [0.70247429],
       [0.70247429],
       [0.70240015],
       [0.7021751 ],
       [0.70182474],
       [0.70168799],
       [0.70161316],
       [0.70138053],
       [0.70138053],
       [0.7012569 ],
       [0.70113425],
       [0.70109549],
       [0.70104884],
       [0.70099975],
       [0.70095629]])

In [17]:
np.array(angles_list1)

array([[0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69497067],
       [0.69497067],
       [0.69497067],
       [0.69497067],
       [0.69497067],
       [0.69509865],
       [0.69540432],
       [0.69569221],
       [0.69572368],
       [0.69580986],
       [0.69594116],
       [0.6960172 ],
       [0.69615276],
       [0.69615276],
       [0.69621024],
       [0.69624421],
       [0.69626431],
       [0.6962773 ]])