In [1]:
import numpy as np

import sensors
import em_stoch
import subspace_methods

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12

failing_sensors1 = np.arange(5)
gap_ratio1 = 0.5 * np.ones_like(failing_sensors1, dtype=np.float32)

theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sensors.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sensors.initial_Cov(X1_with_mv)
MUSIC_theta1 = subspace_methods.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sensors.SNR(A1, P_1, Q_1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em_stoch.multistart_EM2(X1_with_mv, 
                                                                               Num_emitters1, 
                                                                               Q=Q_1,
                                                                               MUSIC_theta=MUSIC_theta1, 
                                                                               num_of_starts=10, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Initial angles = [0.71558499]
likelihood is -870.3064393934375 on iteration 0
likelihood is -870.2041431524815 on iteration 1
likelihood is -870.0947127015846 on iteration 2
likelihood is -869.9829650314755 on iteration 3
likelihood is -869.8631389374502 on iteration 4
likelihood is -869.732338909426 on iteration 5
likelihood is -869.5880976817277 on iteration 6
likelihood is -869.423387182211 on iteration 7
likelihood is -869.2299997523312 on iteration 8
likelihood is -868.9973669839152 on iteration 9
likelihood is -868.7044474273923 on iteration 10
likelihood is -868.3232296553975 on iteration 11
likelihood is -867.8035530480352 on iteration 12
likelihood is -867.0597215364044 on iteration 13
likelihood is -865.9380999308046 on iteration 14
likelihood is -864.166730699395 on iteration 15
likelihood is -861.3327453704144 on iteration 16
likelihood is -857.1913255327536 on iteration 17
likelihood is -852.825090233927 on

In [7]:
EM_theta1_rad, EM_P1

(array([0.69622052]), array([[0.85799732+0.j]]))

In [8]:
em_stoch.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q_1), em_stoch.incomplete_lkhd(X1_with_mv, theta1_rad, P_1, Q_1)

(np.float64(-850.5912048949534), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11

failing_sensors2 = np.arange(8)
gap_ratio2 = 0.5 * np.ones_like(failing_sensors2, dtype=np.float32)

theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P_2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q_2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
N2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sensors.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sensors.initial_Cov(X2_with_mv)
MUSIC_theta2 = subspace_methods.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sensors.SNR(A2, P_2, Q_2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em_stoch.multistart_EM2(X2_with_mv, 
                                                                               Num_emitters2, 
                                                                               Q=Q_2,
                                                                               MUSIC_theta=MUSIC_theta2, 
                                                                               num_of_starts=20, 
                                                                               max_iter=20, 
                                                                               rtol=1e-5)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Initial angles = [0.72431164]
likelihood is -689.483063070951 on iteration 0
likelihood is -689.3738901161959 on iteration 1
likelihood is -689.2567674505078 on iteration 2
likelihood is -689.1365396927348 on iteration 3
likelihood is -689.0017102194244 on iteration 4
likelihood is -688.8541841252711 on iteration 5
likelihood is -688.6844059921156 on iteration 6
likelihood is -688.4839198627712 on iteration 7
likelihood is -688.2374045166027 on iteration 8
likelihood is -687.9190217468987 on iteration 9
likelihood is -687.4891125736523 on iteration 10
likelihood is -686.8741744426684 on iteration 11
likelihood is -685.9421342613443 on iteration 12
likelihood is -684.4515773012034 on iteration 13
likelihood is -682.0211541351272 on iteration 14
likelihood is -678.4069319584889 on iteration 15
likelihood is -674.6642493596522 on iteration 16
likelihood is -673.0752083504324 on iteration 17
1-th start
theta=[0.76634416],P=[

In [13]:
EM_theta2_rad, EM_P2

(array([0.70113191]), array([[0.72904085+0.j]]))

In [14]:
em_stoch.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q_2), em_stoch.incomplete_lkhd(X2_with_mv, theta2_rad, P_2, Q_2)

(np.float64(-673.0621163776358), np.float64(-673.6467390084401))

In [15]:
lhd_list2

[np.float64(-689.4657255022213),
 np.float64(-689.352003354143),
 np.float64(-689.2355598808695),
 np.float64(-689.1133756258208),
 np.float64(-688.981655001269),
 np.float64(-688.8353711868),
 np.float64(-688.6671416134707),
 np.float64(-688.4674256889805),
 np.float64(-688.220321537798),
 np.float64(-687.900841406058),
 np.float64(-687.4662627314092),
 np.float64(-686.8430806323662),
 np.float64(-685.8965118722779),
 np.float64(-684.3805269900954),
 np.float64(-681.9111115014546),
 np.float64(-678.2646855619923),
 np.float64(-674.5622247063485),
 np.float64(-673.0621163776358)]

In [16]:
np.array(angles_list2)

array([[0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.7029336 ],
       [0.70257297],
       [0.70257297],
       [0.70257297],
       [0.70257297],
       [0.70221245],
       [0.70185204],
       [0.70168799],
       [0.70146034],
       [0.70136837],
       [0.70130055],
       [0.7012086 ],
       [0.70113191]])

In [17]:
np.array(angles_list1)

array([[0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69420695],
       [0.69429837],
       [0.69438979],
       [0.69448122],
       [0.69465691],
       [0.69483263],
       [0.69500838],
       [0.69527219],
       [0.69550707],
       [0.69574199],
       [0.69583353],
       [0.69592506],
       [0.69601661],
       [0.69610816],
       [0.69614725],
       [0.69618817],
       [0.69622052]])