In [1]:
import numpy as np

import sensors as sn
import em_tools as em
import subspace_methods as sm

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12

failing_sensors1 = np.arange(5)
gap_ratio1 = 0.5 * np.ones_like(failing_sensors1, dtype=np.float32)

theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sn.gss(Num_emitters1, sample_size1, P1)
N1 = sn.gss(Num_sensors1, sample_size1, Q1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sn.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sn.initial_Cov(X1_with_mv)
MUSIC_theta1 = sm.MUSIC_DoA(R1, Num_emitters1)

In [4]:
MUSIC_theta1

array([0.71558499])

In [5]:
sn.SNR(A1, P1, Q1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [6]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em.multistart_EM2(X1_with_mv, 
                                                                         Num_emitters1, 
                                                                         Q=Q1,
                                                                         theta_guess=MUSIC_theta1, 
                                                                         num_of_starts=10, 
                                                                         max_iter=20, 
                                                                         rtol=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Iteration=0
likelihood is -870.3909570216754 on iteration 0.
Iteration=1
likelihood is -870.3814469960676 on iteration 1.
Iteration=2
likelihood is -870.3718879745038 on iteration 2.
Iteration=3
likelihood is -870.3599271548069 on iteration 3.
Iteration=4
likelihood is -870.3495571065747 on iteration 4.
Iteration=5
likelihood is -870.3389961994174 on iteration 5.
Iteration=6
likelihood is -870.3259350663559 on iteration 6.
Iteration=7
likelihood is -870.3138719805875 on iteration 7.
Iteration=8
likelihood is -870.3013999859351 on iteration 8.
Iteration=9
likelihood is -870.2884840541122 on iteration 9.
Iteration=10
likelihood is -870.2753401616369 on iteration 10.
Iteration=11
likelihood is -870.2614988339282 on iteration 11.
Iteration=12
likelihood is -870.2468265149835 on iteration 12.
Iteration=13
likelihood is -870.231163762605 on iteration 13.
Iteration=14
likelihood is -870.2143180299817 on iteration 14.
Iteration

In [7]:
EM_theta1_rad, EM_P1

(array([0.69420695]), array([[0.00290927+0.j]]))

In [8]:
em.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q1), em.incomplete_lkhd(X1_with_mv, theta1_rad, P1, Q1)

(np.float64(-870.0971079943116), np.float64(-852.4011191641745))

In [9]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11

failing_sensors2 = np.arange(8)
gap_ratio2 = 0.5 * np.ones_like(failing_sensors2, dtype=np.float32)

theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sn.gss(Num_emitters2, sample_size2, P2)
N2 = sn.gss(Num_sensors2, sample_size2, Q2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sn.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sn.initial_Cov(X2_with_mv)
MUSIC_theta2 = sm.MUSIC_DoA(R2, Num_emitters2)

In [10]:
MUSIC_theta2

array([0.72431164])

In [11]:
sn.SNR(A2, P2, Q2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [12]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em.multistart_EM2(X2_with_mv, 
                                                                         Num_emitters2, 
                                                                         Q=Q2,
                                                                         theta_guess=MUSIC_theta2, 
                                                                         num_of_starts=20, 
                                                                         max_iter=20, 
                                                                         rtol=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Iteration=0
likelihood is -689.5691426530494 on iteration 0.
Iteration=1
likelihood is -689.559471069902 on iteration 1.
Iteration=2
likelihood is -689.547368542294 on iteration 2.
Iteration=3
likelihood is -689.5344206660517 on iteration 3.
Iteration=4
likelihood is -689.5229973752716 on iteration 4.
Iteration=5
likelihood is -689.5113029767524 on iteration 5.
Iteration=6
likelihood is -689.4984381855377 on iteration 6.
Iteration=7
likelihood is -689.4850034148457 on iteration 7.
Iteration=8
likelihood is -689.4709289727629 on iteration 8.
Iteration=9
likelihood is -689.456208714154 on iteration 9.
Iteration=10
likelihood is -689.4410772514203 on iteration 10.
Iteration=11
likelihood is -689.4248467612551 on iteration 11.
Iteration=12
likelihood is -689.4072672592796 on iteration 12.
Iteration=13
likelihood is -689.3880254837283 on iteration 13.
Iteration=14
likelihood is -689.3667225303005 on iteration 14.
Iteration=15

In [13]:
EM_theta2_rad, EM_P2

(array([0.70303333]), array([[0.00341951+0.j]]))

In [14]:
em.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q2), em.incomplete_lkhd(X2_with_mv, theta2_rad, P2, Q2)

(np.float64(-689.1950560928265), np.float64(-673.6467390084401))