In [1]:
import numpy as np
import sensors
import ecm_determ

In [2]:
dist_ratio = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad[0]) # Направление прибытия (DOA) в градусах
Q1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gds(Num_emitters1, sample_size1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

EM_theta1_rad, EM_S, lhd_1 = ecm_determ.multi_start_ECM_kn(X1_with_mv, 1, Q1, 10, max_iter=30, rtol=1e-9)

EM_theta1_deg = np.rad2deg(EM_theta1_rad)
print(f"Погрешность в смысле разности углов в градусах: {np.abs(EM_theta1_deg-theta1_deg)}.\nПогрешность в смысле разности синусов углов {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

In [5]:
EM_theta1_rad, EM_S, EM_Q, lhd_1 = ecm_determ.multi_start_ECM_un(X1_with_mv, 1, num_of_starts=10, max_iter=20, rtol=1e-6)

0-th start
Initial theta = [-2.83488836]
Q=[[1.0121385  0.         0.         0.         0.        ]
 [0.         1.16042865 0.         0.         0.        ]
 [0.         0.         0.83867206 0.         0.        ]
 [0.         0.         0.         1.19758656 0.        ]
 [0.         0.         0.         0.         1.38395114]]
incomplete likelihood is -252.89792976909172 on iteration 0
Q=[[1.10956907 0.         0.         0.         0.        ]
 [0.         1.17642262 0.         0.         0.        ]
 [0.         0.         0.78127608 0.         0.        ]
 [0.         0.         0.         0.99177993 0.        ]
 [0.         0.         0.         0.         1.18654033]]
incomplete likelihood is -494.9466164669903 on iteration 1
Q=[[1.10405198 0.         0.         0.         0.        ]
 [0.         1.23634398 0.         0.         0.        ]
 [0.         0.         0.62080506 0.         0.        ]
 [0.         0.         0.         0.85015215 0.        ]
 [0.         0.     

In [6]:
EM_theta1_rad

array([0.85725044])