In [1]:
import numpy as np
import sensors
import em_stoch

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.7] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Направление прибытия (DOA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация шума
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

In [5]:
EM_theta1_rad, EM_P1, lhd_1 = em_stoch.multi_start_EM(X1_with_mv, Num_emitters1, Q_1, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836]
likelihood is -872.6640071655485 on iteration 0
likelihood is -861.5359890985837 on iteration 1
likelihood is -857.0254158694364 on iteration 2
likelihood is -854.6973016856198 on iteration 3
likelihood is -853.3235064331082 on iteration 4
likelihood is -852.4421538035899 on iteration 5
likelihood is -851.8447363590518 on iteration 6
likelihood is -851.4245091804979 on iteration 7
likelihood is -851.121567429438 on iteration 8
likelihood is -850.8996754817683 on iteration 9
likelihood is -850.7356700506921 on iteration 10
likelihood is -850.6140079266576 on iteration 11
likelihood is -850.524002705794 on iteration 12
likelihood is -850.4578698435432 on iteration 13
likelihood is -850.4100461223225 on iteration 14
likelihood is -850.3764174694344 on iteration 15
likelihood is -850.3537532173704 on iteration 16
likelihood is -850.3396189532858 on iteration 17
likelihood is -850.3321906792313 on iteration 18
likelihood is -850.3300118295863 on iter

In [6]:
EM_theta1_rad

array([0.69329706])

In [7]:
EM_P1

array([[0.99618269]])

In [8]:
EM_theta1_deg = np.rad2deg(EM_theta1_rad)

In [9]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(EM_theta1_deg-theta1_deg)},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.38404989],
Погрешность в смысле разности синусов углов:       [0.00514112].


In [10]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([-0.5, 0.7], dtype=np.float64) # Направление прибытия (DOA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Направление прибытия (DOA) в градусах
P_2 = 1 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация шума
Q_2 = 1.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шума
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
n2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + n2.T).T

In [11]:
X2_with_mv = sensors.MCAR(X2, [2,4], [40, 40])

In [12]:
EM_theta2_rad, EM_P2, lhd_2 = em_stoch.multi_start_EM(X2_with_mv, Num_emitters2, Q_2, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836  0.30670429]
likelihood is -1108.2290969065161 on iteration 0
likelihood is -1034.9498720483464 on iteration 1
likelihood is -975.2799103121716 on iteration 2
likelihood is -922.0021228963005 on iteration 3
likelihood is -874.8620174963905 on iteration 4
likelihood is -836.793809002529 on iteration 5
likelihood is -810.0297080795514 on iteration 6
likelihood is -793.3082030316331 on iteration 7
likelihood is -783.4367848386111 on iteration 8
likelihood is -777.6529618563723 on iteration 9
likelihood is -774.2244277715598 on iteration 10
likelihood is -772.1663548304477 on iteration 11
likelihood is -770.917973842593 on iteration 12
likelihood is -770.1541598488437 on iteration 13
likelihood is -769.6828948452323 on iteration 14
likelihood is -769.3894888137972 on iteration 15
likelihood is -769.2049622721349 on iteration 16
likelihood is -769.0875761136444 on iteration 17
likelihood is -769.0119948797992 on iteration 18
likelihood is -768.9626303

In [13]:
EM_theta2_deg = np.rad2deg(EM_theta2_rad)

In [14]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(np.sort(EM_theta2_deg)-np.sort(theta2_deg))},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta2_rad)-np.sin(theta2_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.5790467 0.626755 ],
Погрешность в смысле разности синусов углов:       [0.00884445 0.00840494].


In [15]:
EM_theta2_rad

array([-0.51010627,  0.68906106])

In [16]:
EM_P2

array([[1.11363365, 0.        ],
       [0.        , 0.95542546]])