In [17]:
import numpy as np
import sensors
import em_stoch

In [18]:
DIST_RATIO = 0.5

In [19]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.7] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Направление прибытия (DOA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация шума
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + n1.T).T

In [20]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

In [21]:
EM_theta1_rad, EM_P1, lhd_1 = em_stoch.multi_start_EM(X1, Num_emitters1, Q_1, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836]
likelihood is -1084.745830993925 on iteration 0
likelihood is -1067.7622827049267 on iteration 1
likelihood is -1061.4103474403887 on iteration 2
likelihood is -1058.3046445419818 on iteration 3
likelihood is -1056.5689225778865 on iteration 4
likelihood is -1055.5212158698762 on iteration 5
likelihood is -1054.852782822986 on iteration 6
likelihood is -1054.4067845809225 on iteration 7
likelihood is -1054.0981383979815 on iteration 8
likelihood is -1053.87833658643 on iteration 9
likelihood is -1053.7172914607193 on iteration 10
likelihood is -1053.5963350443776 on iteration 11
likelihood is -1053.5041598097578 on iteration 12
likelihood is -1053.43298227006 on iteration 13
likelihood is -1053.3767669948909 on iteration 14
likelihood is -1053.3319453802706 on iteration 15
likelihood is -1053.2955410839013 on iteration 16
likelihood is -1053.2657399899736 on iteration 17
likelihood is -1053.2411876840729 on iteration 18
likelihood is -1053.22100

In [22]:
EM_theta1_rad

array([0.69177367])

In [23]:
EM_P1

array([[1.11375748]])

In [24]:
EM_theta1_deg = np.rad2deg(EM_theta1_rad)

In [25]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(EM_theta1_deg-theta1_deg)},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.47133391],
Погрешность в смысле разности синусов углов:       [0.00631357].


In [26]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([-0.5, 0.7], dtype=np.float64) # Направление прибытия (DOA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Направление прибытия (DOA) в градусах
P_2 = 1 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация шума
Q_2 = 1.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шума
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
n2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + n2.T).T

In [27]:
X2_with_mv = sensors.MCAR(X2, [2,4], [40, 40])

In [28]:
EM_theta2_rad, EM_P2, lhd_2 = em_stoch.multi_start_EM(X2, Num_emitters2, Q_2, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836  0.30670429]
likelihood is -1313.3547051920666 on iteration 0
likelihood is -1340.4734389164078 on iteration 1
likelihood is -1274.3519213909076 on iteration 2
likelihood is -1251.8431063467197 on iteration 3
likelihood is -1244.6290091014166 on iteration 4
likelihood is -1242.07647677714 on iteration 5
likelihood is -1240.8099051017598 on iteration 6
likelihood is -1239.9651053882842 on iteration 7
likelihood is -1239.2939298336821 on iteration 8
likelihood is -1238.7091855051347 on iteration 9
likelihood is -1238.1701854592593 on iteration 10
likelihood is -1237.6475535906716 on iteration 11
likelihood is -1237.132652802823 on iteration 12
likelihood is -1236.6003328389043 on iteration 13
likelihood is -1236.0358299370728 on iteration 14
likelihood is -1235.4193503129784 on iteration 15
likelihood is -1234.730711307753 on iteration 16
likelihood is -1233.9565320148063 on iteration 17
likelihood is -1233.0958767470786 on iteration 18
likelihood 

In [29]:
EM_theta2_deg = np.rad2deg(EM_theta2_rad)

In [30]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(np.sort(EM_theta2_deg)-np.sort(theta2_deg))},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta2_rad)-np.sin(theta2_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.75478602 0.50408819],
Погрешность в смысле разности синусов углов:       [0.0115189  0.00675393].


In [31]:
EM_theta2_rad

array([-0.5131735,  0.691202 ])

In [32]:
EM_P2

array([[ 1.16059249,  0.        ],
       [-0.        ,  0.99043561]])