In [59]:
import numpy as np

import sensors

In [60]:
DIST_RATIO = 0.5

In [61]:
Num_sensors1 = 2
Num_emitters1 = 1
sample_size1 = 3
theta1_rad = [0.7] # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
N1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + N1.T).T

In [62]:
X2 = X1.T

In [63]:
X2

array([[ 1.23286261-0.50693947j, -0.75369299-2.56480169j,
        -1.13955941-0.46418469j],
       [-0.01856598-0.92525748j,  0.79798363+0.37228185j,
         0.18908093+0.38559637j]])

In [64]:
B = np.einsum('li,lj->lij', X1, np.conj(X1))

In [65]:
B.shape

(3, 2, 2)

In [66]:
B[0]

array([[1.77693783+0.j        , 0.44616023+1.15012717j],
       [0.44616023-1.15012717j, 0.85644609+0.j        ]])

In [67]:
np.outer(X2[:,0], X2[:,0].conj()) - B[0]

array([[2.22044605e-16+5.07662251e-17j, 0.00000000e+00-2.22044605e-16j],
       [0.00000000e+00+0.00000000e+00j, 0.00000000e+00+4.14505704e-19j]])

In [68]:
np.outer(X2[:,1], X2[:,1].conj()) - B[1]

array([[0.+1.05904201e-17j, 0.+0.00000000e+00j],
       [0.+2.22044605e-16j, 0.+2.69784462e-17j]])

In [69]:
np.outer(X2[:,2], X2[:,2].conj()) - B[2]

array([[0.-5.03330980e-17j, 0.+0.00000000e+00j],
       [0.+0.00000000e+00j, 0.-6.81767277e-18j]])

In [70]:
X1.conj()

array([[ 1.23286261+0.50693947j, -0.01856598+0.92525748j],
       [-0.75369299+2.56480169j,  0.79798363-0.37228185j],
       [-1.13955941+0.46418469j,  0.18908093-0.38559637j]])

In [71]:
V = np.array([[1, 2, 3], [4, 1, 2]])

In [72]:
W = np.array([[5, 2, 1], [0, 3, 7]])

In [73]:
np.einsum('li,lj -> lij', V, W)

array([[[ 5,  2,  1],
        [10,  4,  2],
        [15,  6,  3]],

       [[ 0, 12, 28],
        [ 0,  3,  7],
        [ 0,  6, 14]]])

In [74]:
W = np.zeros((3, 5, 5), dtype=np.complex128)

In [75]:
E_i = [1, 4]

In [76]:
G = np.array([[7, 5],[3, 8]])

In [77]:
W[np.ix_([2], E_i, E_i)] += G

In [78]:
Q = np.zeros((3,2,2))

In [79]:
Q[0, 0, 0] = 2
Q[0, 1, 1] = 2

Q[1, 0, 0] = 5
Q[1, 1, 1] = 7

Q[2, 0, 0] = 9
Q[2, 1, 1] = 9

In [80]:
np.linalg.inv(Q)

array([[[0.5       , 0.        ],
        [0.        , 0.5       ]],

       [[0.2       , 0.        ],
        [0.        , 0.14285714]],

       [[0.11111111, 0.        ],
        [0.        , 0.11111111]]])

In [81]:
Q

array([[[2., 0.],
        [0., 2.]],

       [[5., 0.],
        [0., 7.]],

       [[9., 0.],
        [0., 9.]]])

In [82]:
# Примерные данные
M, L, G = 4, 5, 2
K_ZX = np.random.rand(M, L)  # Матрица K_ZX размером MxL
K_XX_inv = np.random.rand(G, L, L)  # Матрица K_XX_inv размером GxLxL
X_modified = np.random.rand(L, G)  # Матрица X_modified размером LxG

In [83]:
A = K_ZX @ K_XX_inv

In [84]:
A.shape

(2, 4, 5)

In [85]:
np.einsum('gml,lg->mg', A, X_modified)

array([[2.12575936, 2.36748662],
       [3.03829982, 4.27622891],
       [3.85732101, 5.03374399],
       [2.19425038, 2.53410278]])

In [86]:
K_XZ = K_ZX.T

In [87]:
K_XZ

array([[0.22348501, 0.08096274, 0.38087896, 0.24767327],
       [0.49521418, 0.50990261, 0.74481274, 0.50722963],
       [0.52509143, 0.04633654, 0.44511734, 0.28617055],
       [0.13027579, 0.68525258, 0.24411658, 0.2927107 ],
       [0.05062786, 0.58621867, 0.7352176 , 0.0531478 ]])

In [89]:
C = A @ K_XZ