In [1]:
import numpy as np

In [2]:
from pathlib import Path
import sys

try:
    ROOT = Path().resolve().parents[1]
    assert (ROOT / "common").exists()
except AssertionError:
    ROOT = next(p for p in Path().resolve().parents if (p / "common").exists())

if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

In [3]:
#print(ROOT)

In [4]:
from common import sensors as sn 
from common import subspace_methods as sm
import em_tools as em

In [5]:
DIST_RATIO = 0.5

In [6]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12

failing_sensors1 = np.arange(5)
gap_ratio1 = 0.5 * np.ones_like(failing_sensors1, dtype=np.float32)

theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sn.gss(Num_emitters1, sample_size1, P1)
N1 = sn.gss(Num_sensors1, sample_size1, Q1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sn.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sn.initial_Cov(X1_with_mv)
MUSIC_theta1 = sm.MUSIC_DoA(R1, Num_emitters1)

In [7]:
MUSIC_theta1

array([0.71558499])

In [8]:
sn.SNR(A1, P1, Q1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [9]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = em.multistart_EM2(X1_with_mv, 
                                                                         Num_emitters1, 
                                                                         Q=Q1,
                                                                         theta_guess=MUSIC_theta1, 
                                                                         num_of_starts=10, 
                                                                         max_iter=20, 
                                                                         rtol=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Inital likelihood = -870.4011155592349
Iteration=1
likelihood is -870.3917920097845 on iteration 1.
Iteration=2
likelihood is -870.3817423165093 on iteration 2.
Iteration=3
likelihood is -870.3709881346135 on iteration 3.
Iteration=4
likelihood is -870.3599315768512 on iteration 4.
Iteration=5
likelihood is -870.3486576579278 on iteration 5.
Iteration=6
likelihood is -870.3372214664555 on iteration 6.
Iteration=7
likelihood is -870.3255491077532 on iteration 7.
Iteration=8
likelihood is -870.3135995430688 on iteration 8.
Iteration=9
likelihood is -870.3013153055845 on iteration 9.
Iteration=10
likelihood is -870.2885911765383 on iteration 10.
Iteration=11
likelihood is -870.2752944715131 on iteration 11.
Iteration=12
likelihood is -870.2613316764638 on iteration 12.
Iteration=13
likelihood is -870.2465373228381 on iteration 13.
Iteration=14
likelihood is -870.2307812896312 on iteration 14.
Iteration=15
likelihood is -87

In [10]:
EM_theta1_rad, EM_P1

(array([0.69625316]), array([[0.00291105+0.j]]))

In [11]:
em.incomplete_lkhd(X1_with_mv, EM_theta1_rad, EM_P1, Q1), em.incomplete_lkhd(X1_with_mv, theta1_rad, P1, Q1)

(np.float64(-870.096502715453), np.float64(-852.4011191641745))

In [12]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11

failing_sensors2 = np.arange(8)
gap_ratio2 = 0.5 * np.ones_like(failing_sensors2, dtype=np.float32)

theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sn.gss(Num_emitters2, sample_size2, P2)
N2 = sn.gss(Num_sensors2, sample_size2, Q2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sn.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sn.initial_Cov(X2_with_mv)
MUSIC_theta2 = sm.MUSIC_DoA(R2, Num_emitters2)

In [13]:
MUSIC_theta2

array([0.72431164])

In [14]:
sn.SNR(A2, P2, Q2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [15]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = em.multistart_EM2(X2_with_mv, 
                                                                         Num_emitters2, 
                                                                         Q=Q2,
                                                                         theta_guess=MUSIC_theta2, 
                                                                         num_of_starts=20, 
                                                                         max_iter=20, 
                                                                         rtol=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Inital likelihood = -689.5792611594288
Iteration=1
likelihood is -689.5691426530494 on iteration 1.
Iteration=2
likelihood is -689.5583380649606 on iteration 2.
Iteration=3
likelihood is -689.5468378630277 on iteration 3.
Iteration=4
likelihood is -689.534921465554 on iteration 4.
Iteration=5
likelihood is -689.5227543532703 on iteration 5.
Iteration=6
likelihood is -689.5102895341357 on iteration 6.
Iteration=7
likelihood is -689.4974409215903 on iteration 7.
Iteration=8
likelihood is -689.4842037655498 on iteration 8.
Iteration=9
likelihood is -689.4704015336896 on iteration 9.
Iteration=10
likelihood is -689.4558870575754 on iteration 10.
Iteration=11
likelihood is -689.4405117743823 on iteration 11.
Iteration=12
likelihood is -689.4240330130519 on iteration 12.
Iteration=13
likelihood is -689.4062374024287 on iteration 13.
Iteration=14
likelihood is -689.3867712284027 on iteration 14.
Iteration=15
likelihood is -689.

In [16]:
EM_theta2_rad, EM_P2

(array([0.70117835]), array([[0.00342784+0.j]]))

In [17]:
em.incomplete_lkhd(X2_with_mv, EM_theta2_rad, EM_P2, Q2), em.incomplete_lkhd(X2_with_mv, theta2_rad, P2, Q2)

(np.float64(-689.193567005708), np.float64(-673.6467390084401))