In [1]:
import numpy as np

In [2]:
from pathlib import Path
import sys

try:
    ROOT = Path().resolve().parents[1]
    assert (ROOT / "common").exists()
except AssertionError:
    ROOT = next(p for p in Path().resolve().parents if (p / "common").exists())

if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

In [3]:
#print(ROOT)

In [4]:
from common import sensors as sn 
from common import subspace_methods as sm
from common import map_em_tools as met
from common import log_funcs as lf

In [5]:
DIST_RATIO = 0.5

In [6]:
Num_sensors1 = 25
Num_emitters1 = 1
sample_size1 = 12

failing_sensors1 = np.arange(5)
gap_ratio1 = 0.5 * np.ones_like(failing_sensors1, dtype=np.float32)

theta1_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Угловые координаты источников (DoA) в градусах
P1 = 0.5 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация сигналов
Q1 = 8.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шумов
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S1 = sn.gss(Num_emitters1, sample_size1, P1)
N1 = sn.gss(Num_sensors1, sample_size1, Q1)
X1 = (A1 @ S1.T + N1.T).T
X1_with_mv = sn.MCAR(X1, failing_sensors1, gap_ratio1)
R1 = sn.initial_Cov(X1_with_mv)
MUSIC_theta1 = sm.MUSIC_DoA(R1, Num_emitters1)

Psi = 1.1 * P1
nu = 10 * P1.shape[0]

In [7]:
MUSIC_theta1

array([0.71558499])

In [8]:
sn.SNR(A1, P1, Q1, metrics = 'avg', scale = 'linear')

np.float64(1.54320987654321)

In [9]:
EM_theta1_rad, EM_P1, lhd_1, lhd_list1, angles_list1 = met.multistart_EM(X1_with_mv, 
                                                                         Num_emitters1, 
                                                                         Q=Q1,
                                                                         theta_guess=MUSIC_theta1,
                                                                         Psi=Psi,
                                                                         nu=nu, 
                                                                         num_of_starts=10, 
                                                                         max_iter=20, 
                                                                         rtol_params=1e-6,
                                                                         rtol_lkhd=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.71558499],P=[[1.18642836e-07-1.98523347e-24j]]
Inital log_posterior = -4636457.408280083
Iteration=1
new_angles=[0.72207638]
new_P:
[[0.02401335+0.j]]
Log_posterior is -850.3513688421477 on iteration 1.
Iteration=2
new_angles=[0.71688292]
new_P:
[[0.02542536+0.j]]
Log_posterior is -849.4525412302517 on iteration 2.
Iteration=3
new_angles=[0.71277335]
new_P:
[[0.02555941+0.j]]
Log_posterior is -849.2858397343188 on iteration 3.
Iteration=4
new_angles=[0.70952274]
new_P:
[[0.02559291+0.j]]
Log_posterior is -849.2037138247634 on iteration 4.
Iteration=5
new_angles=[0.70695118]
new_P:
[[0.02561324+0.j]]
Log_posterior is -849.1512088178622 on iteration 5.
Iteration=6
new_angles=[0.7048829]
new_P:
[[0.02562889+0.j]]
Log_posterior is -849.115675777937 on iteration 6.
Iteration=7
new_angles=[0.70323773]
new_P:
[[0.02564188+0.j]]
Log_posterior is -849.0913161189603 on iteration 7.
Iteration=8
new_angles=[0.7019037]
new_P:
[[0.02565314+0.j]]
Log_posterior is -849.073971502927

In [10]:
EM_theta1_rad, EM_P1

(array([0.69626801]), array([[0.02575831+0.j]]))

In [11]:
lf.log_posterior(X1_with_mv, EM_theta1_rad, EM_P1, Q1, Psi, nu), lf.log_posterior(X1_with_mv, theta1_rad, P1, Q1, Psi, nu)

(np.float64(-849.0003203643121), np.float64(-845.876500178015))

In [12]:
Num_sensors2 = 25
Num_emitters2 = 1
sample_size2 = 11

failing_sensors2 = np.arange(8)
gap_ratio2 = 0.5 * np.ones_like(failing_sensors2, dtype=np.float32)

theta2_rad = np.array([0.7]) # Угловые координаты источников (DoA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Угловые координаты источников (DoA) в градусах
P2 = 0.5 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация сигналов
Q2 = 6.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шумов
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица векторов направленности
# Генерация сигналов, шумов и наблюдений
S2 = sn.gss(Num_emitters2, sample_size2, P2)
N2 = sn.gss(Num_sensors2, sample_size2, Q2)
X2 = (A2 @ S2.T + N2.T).T
X2_with_mv = sn.MCAR(X2, failing_sensors2, gap_ratio2)
R2 = sn.initial_Cov(X2_with_mv)
MUSIC_theta2 = sm.MUSIC_DoA(R2, Num_emitters2)

In [13]:
MUSIC_theta2

array([0.72431164])

In [14]:
sn.SNR(A2, P2, Q2, metrics = 'avg', scale = 'linear')

np.float64(2.0491803278688523)

In [15]:
EM_theta2_rad, EM_P2, lhd_2, lhd_list2, angles_list2 = met.multistart_EM(X2_with_mv, 
                                                                         Num_emitters2, 
                                                                         Q=Q2,
                                                                         theta_guess=MUSIC_theta2,   
                                                                         Psi=Psi,
                                                                         nu=nu,
                                                                         num_of_starts=20, 
                                                                         max_iter=20, 
                                                                         rtol_params=1e-6,
                                                                         rtol_lkhd=1e-6,
                                                                         reg_coef=1e-4)

0-th start
theta=[0.72431164],P=[[7.5917774e-08+4.13590306e-24j]]
Inital log_posterior = -7245189.527913359
Iteration=1
new_angles=[0.72431164]
new_P:
[[0.02510022+0.j]]
Log_posterior is -668.7759243218117 on iteration 1.
Iteration=2
new_angles=[0.71999701]
new_P:
[[0.02673966+0.j]]
Log_posterior is -667.8656149686985 on iteration 2.
Iteration=3
new_angles=[0.71650773]
new_P:
[[0.02691798+0.j]]
Log_posterior is -667.6941735534044 on iteration 3.
Iteration=4
new_angles=[0.71367475]
new_P:
[[0.0269685+0.j]]
Log_posterior is -667.6082046008988 on iteration 4.
Iteration=5
new_angles=[0.71136847]
new_P:
[[0.02700219+0.j]]
Log_posterior is -667.5500199204613 on iteration 5.
Iteration=6
new_angles=[0.70948859]
new_P:
[[0.02703035+0.j]]
Log_posterior is -667.5082541644447 on iteration 6.
Iteration=7
new_angles=[0.70796109]
new_P:
[[0.02705525+0.j]]
Log_posterior is -667.4775123956045 on iteration 7.
Iteration=8
new_angles=[0.70671576]
new_P:
[[0.02707797+0.j]]
Log_posterior is -667.45416081156

In [16]:
EM_theta2_rad, EM_P2

(array([0.70113993]), array([[0.02730827+0.j]]))

In [17]:
lf.log_posterior(X2_with_mv, EM_theta2_rad, EM_P2, Q2, Psi, nu), lf.log_posterior(X2_with_mv, theta2_rad, P2, Q2, Psi, nu)

(np.float64(-667.3258168558082), np.float64(-667.1221200222807))