In [1]:
import numpy as np
import sensors
import em_stoch

In [2]:
DIST_RATIO = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.7] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad) # Направление прибытия (DOA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация шума
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors1).reshape(-1,1) * 
             np.sin(theta1_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gss(Num_emitters1, sample_size1, P_1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

In [5]:
EM_theta1_rad, EM_P1, lhd_1 = em_stoch.multi_start_EM(X1_with_mv, Num_emitters1, Q_1, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836]
likelihood is -872.664631803558 on iteration 0
likelihood is -859.7887684103226 on iteration 1
likelihood is -855.3005904807089 on iteration 2
likelihood is -853.2001023822344 on iteration 3
likelihood is -852.0840307855716 on iteration 4
likelihood is -851.4529170724219 on iteration 5
likelihood is -851.0821695486223 on iteration 6
likelihood is -850.8622953512988 on iteration 7
likelihood is -850.7340249096292 on iteration 8
likelihood is -850.663300344118 on iteration 9
likelihood is -850.6283605471999 on iteration 10
likelihood is -850.6192729432927 on iteration 11
likelihood is -850.6252831997372 on iteration 12
likelihood is -850.6489565293446 on iteration 13
likelihood is -850.6735928819458 on iteration 14
likelihood is -850.6971859592458 on iteration 15
likelihood is -850.7265909324369 on iteration 16
likelihood is -850.7610136205905 on iteration 17
likelihood is -850.7939967064883 on iteration 18
likelihood is -850.8234583390417 on iter

In [6]:
EM_theta1_rad

array([0.69520188])

In [7]:
EM_P1

array([[0.98692967]])

In [8]:
EM_theta1_deg = np.rad2deg(EM_theta1_rad)

In [9]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(EM_theta1_deg-theta1_deg)},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.27491193],
Погрешность в смысле разности синусов углов:       [0.0036772].


In [10]:
Num_sensors2 = 5
Num_emitters2 = 2
sample_size2 = 100
theta2_rad = np.array([-0.5, 0.7], dtype=np.float64) # Направление прибытия (DOA) в радианах
theta2_deg = np.rad2deg(theta2_rad) # Направление прибытия (DOA) в градусах
P_2 = 1 * np.eye(Num_emitters2, dtype=np.float64) # Ковариация шума
Q_2 = 1.1 * np.eye(Num_sensors2, dtype=np.float64) # Ковариация шума
A2 = (np.exp(-2j * np.pi * DIST_RATIO * np.arange(Num_sensors2).reshape(-1,1) * 
             np.sin(theta2_rad))) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S2 = sensors.gss(Num_emitters2, sample_size2, P_2)
n2 = sensors.gss(Num_sensors2, sample_size2, Q_2)
X2 = (A2 @ S2.T + n2.T).T

In [11]:
X2_with_mv = sensors.MCAR(X2, [2,4], [40, 40])

In [12]:
EM_theta2_rad, EM_P2, lhd_2 = em_stoch.multi_start_EM(X2_with_mv, Num_emitters2, Q_2, 10, 
                                                         max_iter=20, 
                                                         rtol=1e-3)

0-th start
Initial theta = [-2.83488836  0.30670429]
likelihood is -1108.2354823673677 on iteration 0
likelihood is -1142.973007639441 on iteration 1
likelihood is -1049.5449850338005 on iteration 2
likelihood is -1019.1689648173003 on iteration 3
likelihood is -1007.0795799159147 on iteration 4
likelihood is -1194.965839880332 on iteration 5
likelihood is -1066.258207420286 on iteration 6
likelihood is -963.4742580829553 on iteration 7
likelihood is -889.1816799186954 on iteration 8
likelihood is -841.4896424147155 on iteration 9
likelihood is -810.1622313409481 on iteration 10
likelihood is -791.3781361706862 on iteration 11
likelihood is -781.0513165018974 on iteration 12
likelihood is -775.5139373961151 on iteration 13
likelihood is -772.5432897164603 on iteration 14
likelihood is -770.929753408808 on iteration 15
likelihood is -770.0450994391291 on iteration 16
likelihood is -769.5592909561819 on iteration 17
likelihood is -769.2883379996147 on iteration 18
likelihood is -769.1341

In [13]:
EM_theta2_deg = np.rad2deg(EM_theta2_rad)

In [14]:
print(f"Погрешность в смысле разности углов в градусах: \
      {np.abs(np.sort(EM_theta2_deg)-np.sort(theta2_deg))},")
print(f"Погрешность в смысле разности синусов углов: \
      {np.abs(np.sin(EM_theta2_rad)-np.sin(theta2_rad))}.")

Погрешность в смысле разности углов в градусах:       [0.38624439 0.41602728],
Погрешность в смысле разности синусов углов:       [0.00590505 0.00557049].


In [15]:
EM_theta2_rad

array([-0.50674124,  0.69273895])

In [16]:
EM_P2

array([[1.12134419, 0.        ],
       [0.        , 0.96737365]])