# ECM-алгоритм для случая, когда шум известен, а сигналы предполагаются стохастическими

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import em_stools
from functools import partial

In [2]:
dist_ratio = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad[0]) # Направление прибытия (DOA) в градусах
P_1 = 1 * np.eye(Num_emitters1, dtype=np.float64) # Ковариация шума
Q_1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = em_stools.gss(Num_emitters1, sample_size1, P_1)
n1 = em_stools.gss(Num_sensors1, sample_size1, Q_1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
S1.shape

(100, 1)

In [5]:
X1_with_mv = em_stools.MCAR(X1, [2,4], [40, 40])

In [6]:
#EM_theta1_rad, lhd_1 = em_stools.multi_start_EM(X1, 1, Q_1, 10, max_iter=10, eps=1e-6)

In [7]:
#EM_theta1_deg = np.rad2deg(EM_theta1_rad)

In [8]:
#print(f"Погрешность в смысле разности углов в градусах: {np.abs(EM_theta1_deg-theta1_deg)}.\nПогрешность в смысле разности синусов углов {np.abs(np.sin(EM_theta1_rad)-np.sin(theta1_rad))}.")

In [30]:
import numpy as np
nu = np.random.RandomState(10).uniform(-np.pi, np.pi)
print(nu)

1.704757879308132


In [42]:
theta = np.array([(nu + i * 2 * np.pi/10)%(2 * np.pi) for i in range(0,10)]) - np.pi

In [43]:
print(nu)
print(theta)

1.704757879308132
[-1.43683477 -0.80851624 -0.18019771  0.44812082  1.07643935  1.70475788
  2.33307641  2.96139494 -2.69347184 -2.0651533 ]


In [44]:
(theta[2]-theta[1])*10/2/np.pi

1.0

In [35]:
nu - np.pi

-1.4368347742816612

In [36]:
A = np.arange(25).reshape(5,5)

In [37]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
A[:,0]

array([ 0,  5, 10, 15, 20])

In [39]:
A[0,:]

array([0, 1, 2, 3, 4])

In [41]:
A[:,0] @ A[:,0]

750