In [1]:
import numpy as np
import sensors

In [2]:
dist_ratio = 0.5

In [3]:
Num_sensors1 = 5
Num_emitters1 = 1
sample_size1 = 100
theta1_rad = [0.5] # Направление прибытия (DOA) в радианах
theta1_deg = np.rad2deg(theta1_rad[0]) # Направление прибытия (DOA) в градусах
Q1 = 1.1 * np.eye(Num_sensors1, dtype=np.float64) # Ковариация шума
A1 = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors1).reshape(-1,1) * np.sin(theta1_rad)) # Матрица управляющих векторов
# Генерация векторов сигнала, шума и принятого сигнала
S1 = sensors.gds(Num_emitters1, sample_size1)
n1 = sensors.gss(Num_sensors1, sample_size1, Q1)
X1 = (A1 @ S1.T + n1.T).T

In [4]:
S1.shape

(100, 1)

In [5]:
n1.shape

(100, 5)

In [6]:
theta = np.array([0.1, 0.7])

In [7]:
sensors.A_ULA(5, theta)

array([[ 1.        +0.j        ,  1.        +0.j        ],
       [ 0.95121811-0.30851923j, -0.43773075-0.8991061j ],
       [ 0.80963177-0.58693815j, -0.61678357+0.78713279j],
       [ 0.58905469-0.80809317j,  0.97770103+0.21000165j],
       [ 0.31100721-0.95040755j, -0.23915604-0.97098115j]])

In [8]:
X1_with_mv = sensors.MCAR(X1, [2,4], [40, 40])

In [10]:
X1_with_mv[:5]

array([[ 1.05307179+1.71682296j,  1.05785934-2.61381633j,
        -0.93495857-1.25498623j, -1.29429317-0.75556759j,
                nan+0.j        ],
       [-1.19989375+1.27142599j,  1.59157263+0.32820543j,
        -0.28105623-1.12704376j, -1.35694606+0.33369889j,
                nan+0.j        ],
       [-1.29671236+1.31983903j, -0.02611514-0.17874368j,
         2.75247909-1.89419191j, -1.76783794-0.58246557j,
                nan+0.j        ],
       [-1.72746532-0.00914096j,  0.62769474+0.58405291j,
         1.282625  -2.61410027j, -1.04885678-1.04925982j,
                nan+0.j        ],
       [-1.01211199+0.14087172j, -0.35762126+1.27305631j,
         2.63372557-0.23279131j,  0.26210414-1.22339463j,
        -0.31368524+0.88212627j]])

In [11]:
np.isnan(X1_with_mv[:5])

array([[False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [12]:
Indicator = np.isnan(X1_with_mv)
col_numbers = np.arange(1, X1_with_mv.shape[1] + 1)
M, O = col_numbers * Indicator - 1, col_numbers * (Indicator == False) - 1