In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sensors import *

In [2]:
dist_ratio = 0.5
Num_sensors = 5
Num_emitters = 2
sample_size = 100
# DOA in degree
theta_degrees = np.array([[20], [70]])
# DOA in suitable form (radian)
theta = theta_degrees / 180 * np.pi
Gamma_signal = np.array([[2,0],[0,3]])
Gamma_noise = 0.1*np.eye(5, dtype=np.float64)

In [3]:
theta

array([[0.34906585],
       [1.22173048]])

In [4]:
A = np.zeros((Num_sensors, Num_emitters),dtype=np.complex128)
for i in range(Num_emitters):
    A[:,i] = np.exp(-2j * np.pi * dist_ratio * np.arange(Num_sensors) * np.sin(theta[i,0]))

In [5]:
A

array([[ 1.        +0.j        ,  1.        +0.j        ],
       [ 0.47618256-0.87934645j, -0.98210585-0.18832978j],
       [-0.54650034-0.83745888j,  0.92906379+0.36991956j],
       [-0.99665042+0.08177982j, -0.8427721 -0.53827054j],
       [-0.40267475+0.91534313j,  0.72631904+0.68735774j]])

In [6]:
s = CN(Num_emitters,sample_size,Gamma_signal)

In [7]:
n = CN(Num_sensors,sample_size,Gamma_noise)

In [8]:
X = np.zeros((sample_size, 5), dtype=np.complex128)
for i in range(sample_size):
    X[i] = A @ s[i] + n[i]

In [9]:
theta_estimate=EM(X, Gamma_signal, Gamma_noise)

Initial theta = [[ 0.90568055]
 [-0.74927934]]
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.64185679e-04j  0.0209793 -9.80015839e-15j]]
theta_new=[[-3.11336781]
 [-2.06537171]]
Iteration=1
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.64185679e-04j  0.0209793 -9.80015839e-15j]]
theta_new=[[-3.11336781]
 [-2.06537171]]
Iteration=2
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.64185679e-04j  0.0209793 -9.80015839e-15j]]
theta_new=[[-3.11336781]
 [-2.06537171]]
Iteration=3
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.64185679e-04j  0.0209793 -9.80015839e-15j]]
theta_new=[[-3.11336781]
 [-2.06537171]]
Iteration=4
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.64185679e-04j  0.0209793 -9.80015839e-15j]]
theta_new=[[-3.11336781]
 [-2.06537171]]
Iteration=5
K=[[ 0.02091006+3.69286540e-15j -0.00472409+9.64185679e-04j]
 [-0.00472409-9.641856

In [10]:
theta_estimate

array([[-3.11336781],
       [-2.06537171]])

In [11]:
theta

array([[0.34906585],
       [1.22173048]])

In [12]:
theta-theta_estimate

array([[3.46243366],
       [3.28710218]])

In [13]:
np.sin(theta_estimate)

array([[-0.0282211 ],
       [-0.88017034]])

In [14]:
np.sin(theta)

array([[0.34202014],
       [0.93969262]])